### ISSUE TITLE
关于表格

### ISSUE THREAD

**Issue by pakey** [mycolorway/simditor#113]
现在的好像没有设置表头的功能 第一行改为th
然后添加新行有没有快捷键，表格很多行点鼠标好累

在建议一个，提供一个全屏和源代码的功能吧
全屏可以专注写作
源代码是有些时候机器的毕竟处理有点死 需要通过修改源代码来修复

**Comment by farthinker** [comment]
@pakey v2.0.5给表格操作增加了快捷键
