### ISSUE TITLE
English Documentation?

### ISSUE THREAD

**Issue by sheharyarn** [mycolorway/simditor#150]
Simditor is an awesome Rich-Text Editor for the web. It needs to be documented in English as well!

**Comment by Tedko** [comment]
@farthinker  did you finish the Eng Doc?

**Comment by farthinker** [comment]
@Tedko I will release English doc in weeks after v2.2.0

**Comment by sheharyarn** [comment]
:+1:

**Comment by farthinker** [comment]
Done. Tutorials about button and extensions are on the way.

**Comment by sheharyarn** [comment]
Awesome! :+1:
