### ISSUE TITLE
NS_ERROR_FAILURE:  firefox 错误

### ISSUE THREAD

**Issue by zyw** [mycolorway/simditor#161]
NS_ERROR_FAILURE:  firefox 错误 V2.0.4版本
```
if (this.util.browser.mozilla) {
      document.execCommand("enableObjectResizing", false, false);
      return document.execCommand("enableInlineTableEditing", false, false);
 }
```
这行的错误不知道是怎么回事？

**Comment by farthinker** [comment]
感谢反馈，在firefox里面执行enableObjectResizing需要先设置：
```
document.designMode = "on"
```
我稍后来修复这个问题

**Comment by zyw** [comment]
在什么地方加合适，让我先用着，没办法我现在是直接不让它走这个分支了。呵呵

**Comment by farthinker** [comment]
@zyw 你用firefox访问这里会报这个错吗？我这里测试好像是正常的
你的firefox版本是多少？系统是什么？

**Comment by zyw** [comment]
firefox版本是34.0.5 操作系统是Windows 7 我是在Ruby on Rails中开发的，报错是点击几下其他页面，再回过来点击包含编辑器页面时报错，刷新一下就好了。

**Comment by zyw** [comment]
···
if (this.util.browser.mozilla) {
      document.execCommand("enableObjectResizing", false, false);
      return document.execCommand("enableInlineTableEditing", false, false);
 }
···
这句代码是什么作用？我把他变成下面这样
```
if (!this.util.browser.mozilla) {
      document.execCommand("enableObjectResizing", false, false);
      return document.execCommand("enableInlineTableEditing", false, false);
 }
```
也没发现什么问题。

**Comment by farthinker** [comment]
这段代码的作用是在firefox里面屏蔽掉contenteditable元素resize image和编辑表格的功能
这个bug原因是：在页面上没有contenteditable元素的时候调用`document.execCommand("enableObjectResizing", false, false)`就会报这个错，也就是说报这个错的时候编辑器的body没有正确的被初始化

**Comment by zyw** [comment]
好的，谢谢。
