### ISSUE TITLE
Firefox浏览器中文IME对valuechanged事件的触发

### ISSUE THREAD

**Issue by tianlu1677** [mycolorway/simditor#162]
在firefox中，测试代码如下：
```coffeescript
editor.on 'valuechanged', ->
  console.log editor.getValue()
```
在编辑器中输入我们（键盘输入women），只能触发一次valuechanged事件，并且只能监听到`w`一个字母
![ebn isry k0md o 7188iq](https://cloud.githubusercontent.com/assets/2594920/5640142/ba886286-965c-11e4-9b02-65edc9680659.jpg)
即使键入空格确定中文输入后，依旧只有一次valuechanged事件
![ey z3lf25 g8mepvmr504](https://cloud.githubusercontent.com/assets/2594920/5640135/a9544f84-965c-11e4-87fa-50ac43383ef9.jpg)

当键入其他内容时，刚才输入的值才能显示：
![0g_c9dkkz 4 74m dl1tig](https://cloud.githubusercontent.com/assets/2594920/5640178/30530fde-965d-11e4-8911-e39535b37a04.jpg)

Chrome则是正常的输出
![ou5b4 4 468 65 pod9 c](https://cloud.githubusercontent.com/assets/2594920/5640220/d8f3789a-965d-11e4-932e-4869585be4da.png)

测试环境：
windows 8.1 x64
Firefox版本
34.0.5
36.0a2
输入法：
windows 8.1自带中文输入法

我也在网上查了一些相关资料，好像firefox对ime的处理有别于其他浏览器，有些ime的输入是不会触发keydown，keyup，input相关或者change事件的，不知道是不是因为这样造成了这个问题。

**Comment by farthinker** [comment]
感谢你的反馈，测试很详细
我暂时还没有想到很好的办法解决firefox下面ime的这个问题，待我先研究一下

**Comment by farthinker** [comment]
@ichord 感谢，考虑换成用input事件来检测输入内容

**Comment by farthinker** [comment]
@tianlu1677 v2.0.7解决了这个问题
