### ISSUE TITLE
关于弹出层和隐藏初始化

### ISSUE THREAD

**Issue by itlizhi** [mycolorway/simditor#166]
如题，在弹出层 和 display:none 时，初始化后 toolbar 的宽度会错乱

**Comment by farthinker** [comment]
@itlizhi Simditor初始化的时候需要计算toolbar的位置（保证toolbar浮动的时候位置不会错），所以建议你在显示弹出框之后再初始化编辑器

**Comment by itlizhi** [comment]
@farthinker  thanks
