### ISSUE TITLE
源码编辑功能

### ISSUE THREAD

**Issue by 9073194** [mycolorway/simditor#167]
源码编辑功能什么时候能出，有没有排期啊，这个很重要的功能的

**Comment by farthinker** [comment]
不少人提过这个需求，我考虑做成官方扩展

**Comment by 9073194** [comment]
呵呵，大概啥时候出呢，时间太久我就自己研究了

**Comment by ichord** [comment]
@9073194 加油。

**Comment by shenqihui** [comment]
+1

**Comment by 0x55aa** [comment]
额 我正要这个功能，自己做了一个，发现一进行setVale 自己编辑的html标签属性 就没了。。来github一看 也有人有这个需求啊 哈哈

**Comment by shenqihui** [comment]
@0x55aa  写了发上来吧。 setValue 的时候他那里有白名单过滤，所以部分标签属性可能没掉了。

**Comment by 0x55aa** [comment]
@shenqihui 我写的很简单，也不实用，就不发了。不然也不会来这里了 哈哈

**Comment by gantoo** [comment]
@farthinker 加油

**Comment by farthinker** [comment]
https://github.com/mycolorway/simditor/pull/196 这个PR增加了一个source按钮，大家试试，有问题在这里反馈

**Comment by shenqihui** [comment]
@farthinker  

hi farthinker.

测试了下源码编辑的功能，发现了个 BUG。 

重现方式如下：

打开 ： http://simditor.tower.im/

然后直接在编辑框输入一个空行，然后点击 source 的按钮，不断切换，会出现一堆的 <p></p> 空元素。

Thanks.

**Comment by 9073194** [comment]
还有一个不知是不是bug ，切换到源码模式修改后再切回去所有的修改没了

**Comment by shenqihui** [comment]
@9073194  
可能不是bug。
因为部分需要自行配置才可以过白名单的，白名单设定在这里有描述，请看：
https://github.com/mycolorway/simditor/pull/177#issuecomment-75069857

**Comment by lvyaojia** [comment]
@farthinker  @shenqihui   :bear:

**Comment by farthinker** [comment]
@shenqihui bug已修复：https://github.com/mycolorway/simditor/commit/8cbd2a150fa13e1ad5b0fb4ce8260edfd5ab7a31

**Comment by shenqihui** [comment]
@farthinker  :+1:
