### ISSUE TITLE
1. 怎样去除图片里的“外链图片”选项，直接点击图片图标就默认是本地上传？ 2.有没有居中按钮？

### ISSUE THREAD

**Issue by chairy11** [mycolorway/simditor#171]
怎样去除图片里的“外链图片”选项，直接点击图片图标就默认是本地上传？

另外，有没有居中按钮？

**Comment by RuochenLyu** [comment]
第一个问题目前没有这个配置，我之后会增加上的。

第二个问题，Simditor 主要是满足 Tower 这个产品的使用，目前来看还没有居中这样的需求，不过你可以自己写个 Simditor 的扩展来实现这个功能。（http://simditor.tower.im/tours/tour-button.html）

**Comment by chairy11** [comment]
哦，谢谢……

**Comment by farthinker** [comment]
@chairy11 v2.0.7增加了一个选项，imageButton，用来自定义图片按钮的功能：http://simditor.tower.im/docs/doc-config.html#anchor-imageButton
