### ISSUE TITLE
這麼來測試.

### ISSUE THREAD

**Issue by iaceob** [mycolorway/simditor#172]
首先鼠標移動到編輯中, 隨便哪一行, 然後點擊功能欄中的代碼
然後按 shift+enter 跳出 pre 到下一行.
然後按 ctrl+a -> enter 這時候編輯器是沒有內容的
然後在點擊功能蘭中的代碼, 測試的結果就出來了.

**Comment by farthinker** [comment]
你用的是Firefox吗，如果是的话你可以试试最新的master分支，之前修正了一个firefox ctrl+a的bug，但是还没有release版本

**Comment by iaceob** [comment]
說的是這個分支吧 gh-pages
用的是 firefox , 親測還是會這樣, ctrl+a 之後 在點擊 編輯器還是會失效

**Comment by farthinker** [comment]
@iaceob 你试试新发布的v2.0.5，修复了这个问题，具体来说是这个commit修复的：https://github.com/mycolorway/simditor/commit/c3c9344f0b8bfbd894ec603b6027537494559f05
