### ISSUE TITLE
cdn

### ISSUE THREAD

**Issue by vvsuperman** [mycolorway/simditor#173]
有cdn可以使用吗？实在太慢

**Comment by farthinker** [comment]
你是说什么慢？simditor.tower.im吗？

**Comment by vvsuperman** [comment]
不是，我自己网站的simditor，有木有cdn加速

**Comment by vvsuperman** [comment]
平准要1.8s左右

**Comment by RuochenLyu** [comment]
@vvsuperman 我把 simditor 提交到了 staticfile 这个 CDN 服务上，等他们审核通过就可以用了。
你可以访问 http://www.staticfile.org/ 这里看下这家 CDN
https://github.com/staticfile/static/pull/226

**Comment by Xuanwo** [comment]
已经通过了

**Comment by vvsuperman** [comment]
没找到呀，给个地址先

**Comment by Xuanwo** [comment]
这个库已经merge了，但是要能从CDN上访问，可能还需要时间
