### ISSUE TITLE
文件上传如何做到跨域支持

### ISSUE THREAD

**Issue by zdsiyan** [mycolorway/simditor#174]
场景是这样的，页面部署在www.xxx.com下，服务端部署在api.xxx.com下，主域相同，子域不同。
其他参数已经通过转发的方式实现了跨域，但文件属于大资源，不能参照这个方法。
搜索资料发现可以用document.domain的方案来设置跨域，链接如下
http://www.cnblogs.com/fredshare/archive/2013/03/09/2951901.html
想问一下Simditor是否支持跨域上传文件，如果支持，要如何设置；如果不支持，是否会增加这个功能？

**Comment by farthinker** [comment]
Simditor的上传基于[simple-uploader](https://github.com/mycolorway/simple-uploader)，simple-uploader使用ajax请求来上传文件。只要服务器配置正确(CORS)ajax请求是支持跨域的，具体可以参考这里：http://www.nczonline.net/blog/2010/05/25/cross-domain-ajax-with-cross-origin-resource-sharing/

**Comment by dannybaby** [comment]
请问 simple-uploader支持跨域需要在客户端配置什么吗，我用jquery-file-upload可以实现跨域上传，说明服务器的CORS是配置没问题的，但是我将simditor里面upload的url同样设为与jquery-file-upload相同的URL，却不能访问！报错！能帮忙解决一下吗？
Remote Address:**:8080
Request URL:http://***:8080/fileUpload/rest/images/20150129/upload/
Request Method:OPTIONS
Status Code:403 Forbidden
Request Headersview source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Headers:accept, x-file-name, content-type
Access-Control-Request-Method:POST
Connection:keep-alive
Host:***:8080
Origin:http://localhost:8080
Referer:http://localhost:8080/community/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Response Headersview source
Content-Length:90
Content-Type:text/plain;charset=ISO-8859-1
Date:Fri, 30 Jan 2015 09:17:24 GMT
Server:Apache-Coyote/1.1


我用jquery-file-upload发同样的request是正确的，我服务器的CORS配置应该没啥问题！
Remote Address:***:8080
Request URL:http://***:8080/fileUpload/rest/images/20150127/upload/
Request Method:OPTIONS
Status Code:200 OK
Request Headersview source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Headers:accept, content-type
Access-Control-Request-Method:POST
Connection:keep-alive
Host:***:8080
Origin:http://localhost:8080
Referer:http://localhost:8080/community/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Response Headersview source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Origin, Accept, X-Requested-With, Content-Range, Content-Disposition, Last-Modified, Content-Description, Content-Type
Access-Control-Allow-Methods:POST, OPTIONS, HEAD, GET, PUT, DELETE
Access-Control-Allow-Origin:http://localhost:8080
Content-Length:0
Date:Fri, 30 Jan 2015 09:23:02 GMT
Server:Apache-Coyote/1.1
