### ISSUE TITLE
改变字体背景颜色

### ISSUE THREAD

**Issue by dannybaby** [mycolorway/simditor#175]
不是字体颜色，而是文字背景颜色，可以考虑加一个吗？这个好扩展吗，本人刚入行不熟悉，如果不做官方扩展，可以给个简单思路吗

**Comment by farthinker** [comment]
我会考虑增加一个荧光笔按钮，不过最近比较忙，可能要春节之后了

**Comment by dannybaby** [comment]
@farthinker 请问这个功能做完了吗

**Comment by farthinker** [comment]
@dannybaby 我忘记了 囧 春节做了源代码编辑的功能 你可以先把这个issue打开

**Comment by dannybaby** [comment]
请问做好了吗

**Comment by farthinker** [comment]
@dannybaby 已经在实施了，别着急

**Comment by lcjnil** [comment]
@dannybaby 看看这个插件满足需求不 https://github.com/mycolorway/simditor-mark
