### ISSUE TITLE
初始化 simditor 编辑器时候，写入 upload 参数，图片 upload某个状态的时候，触发回调事件？

### ISSUE THREAD

**Issue by shenqihui** [mycolorway/simditor#176]
目前我初始化 simditor 编辑器时候的代码：
```javascript
    new Simditor({
      textarea: $('editor'),
      toolbarFloat: true,
      asteImage: true,
      tabIndent: false,
      defaultImage: '/static/images/favicon.ico',
      upload: {
        url: "/file_upload",
        params: {
          csrfmiddlewaretoken: csrfmiddlewaretoken,
          description: '文章图片',
        },
        fileKey: 'file',
        uploadsuccess: function() {
          console.log('llll');
        }
      }
    });
```

现在我想在文件提交成功之后，触发 uploadsuccess 的动作。
看了下：https://github.com/mycolorway/simditor/blob/master/src/buttons/image.coffee#L155 这个部分的源码，目前来说，目测暂无这个功能，请问，是否已经有了，只是我没发现类似接口。

另外我想了想，好像是 [simple-uploader](https://github.com/mycolorway/simple-uploader) 进行的初始化。但是这个也没提供。

如果没有类似现成的接口的话，告诉我需求，我增加下上去。

另外赞一下这个编辑器。

ps: 目前我还做了一个 simditor-attr(https://github.com/shenqihui/simditor-attr) 的插件。→_→，只是 css 还没写。

**Comment by farthinker** [comment]
@shenqihui 你可以试试在editor.uploader上绑定uploadsuccess事件：
```
editor = new Simditor opts
editor.on 'uploadsuccess', (e, file, result) ->
  # do something
```

**Comment by shenqihui** [comment]
原来能这样子。
