### ISSUE TITLE
2.0.5 版本上传本地图片有问题

### ISSUE THREAD

**Issue by ke-pan** [mycolorway/simditor#178]
配置了upload以后仍然无法显示本地上传，换到2.0.0版本就好了

**Comment by farthinker** [comment]
@ke-pan 我这里测试是正常的，你确认一下是否引用了simple-uploader.js

**Comment by Hubu** [comment]
插入图片后 点击图片 出现 size调整框 点击该调整框 就会消失 项目主页的demo中也是如此

**Comment by ke-pan** [comment]
simple-uploader.js 不在zip file里？

**Comment by ke-pan** [comment]
如果你说的是zip包里的uploader.js，那我加了，顺序是不是有要求？我的顺序是，module, simditor, uploader

**Comment by Hubu** [comment]
我注释掉代码的2239行解决了问题

**Comment by ke-pan** [comment]
看来是顺序问题，simditor要放最后
