### ISSUE TITLE
v2.0.5弹框自动隐藏问题

### ISSUE THREAD

**Issue by nigelvon** [mycolorway/simditor#180]
2.0.5版本无论是超链接还是图片focus之后弹出的属性弹框无法操作，一点就会自动隐藏，应该是比较严重的Bug，最新版的Chrome和Firfox都可以复现，用首页的哪个Demo就行。
2.0.4版本则无此问题。

**Comment by nigelvon** [comment]
经过diff，发现是2231行代码的问题
v2.0.4 this.hidePopover;
v2.0.5 this.hidePopover();

**Comment by farthinker** [comment]
@nigelvon 最新的commit修复了这个问题，稍后我会发布一个hotfix新版本
