### ISSUE TITLE
图片上传有bug

### ISSUE THREAD

**Issue by Hubu** [mycolorway/simditor#181]
![image](https://cloud.githubusercontent.com/assets/4191389/5953076/66891cac-a7be-11e4-9644-8ae6fbb2b342.png)

如上图所示uploader文件中104行的判断中有异步方法（发生在fileread的过程中），因此该条件的失败并不能阻止下面代码的正常执行

**Comment by farthinker** [comment]
@Hubu 这不是bug。异步的readImageFile只用于加载缩略图，是独立的逻辑，是否取消上传的逻辑不应该写在readImageFile的回调里面。
