### ISSUE TITLE
关于跨域上传，求解答

### ISSUE THREAD

**Issue by dannybaby** [mycolorway/simditor#182]
请问 simple-uploader支持跨域需要在客户端配置什么吗，我用jquery-file-upload可以实现跨域上传，说明服务器的CORS是配置没问题的，但是我将simditor里面upload的url同样设为与jquery-file-upload相同的URL，却不能访问！报错！能帮忙解决一下吗？
Remote Address::8080
Request URL:http://:8080/fileUpload/rest/images/20150129/upload/
Request Method:OPTIONS
Status Code:403 Forbidden
Request Headersview source
Accept:/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Headers:accept, x-file-name, content-type
Access-Control-Request-Method:POST
Connection:keep-alive
Host:***:8080
Origin:http://localhost:8080
Referer:http://localhost:8080/community/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Response Headersview source
Content-Length:90
Content-Type:text/plain;charset=ISO-8859-1
Date:Fri, 30 Jan 2015 09:17:24 GMT
Server:Apache-Coyote/1.1

我用jquery-file-upload发同样的request是正确的，我服务器的CORS配置应该没啥问题！
Remote Address::8080
Request URL:http://:8080/fileUpload/rest/images/20150127/upload/
Request Method:OPTIONS
Status Code:200 OK
Request Headersview source
Accept:/
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Headers:accept, content-type
Access-Control-Request-Method:POST
Connection:keep-alive
Host:***:8080
Origin:http://localhost:8080
Referer:http://localhost:8080/community/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Response Headersview source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Origin, Accept, X-Requested-With, Content-Range, Content-Disposition, Last-Modified, Content-Description, Content-Type
Access-Control-Allow-Methods:POST, OPTIONS, HEAD, GET, PUT, DELETE
Access-Control-Allow-Origin:http://localhost:8080
Content-Length:0
Date:Fri, 30 Jan 2015 09:23:02 GMT
Server:Apache-Coyote/1.1

**Comment by farthinker** [comment]
@dannybaby 应该不会是simple-uploader的问题，你自己再检查一下吧。实际上在我们的自己的项目里，我们就是用simple-uploader直接跨域往第三方文件服务器上传文件的。

**Comment by dannybaby** [comment]
那请问你们第三方文件服务器也是用CORS配置吗，能方便透露一下大概怎么配的吗？

**Comment by farthinker** [comment]
@dannybaby 我们使用的是七牛的文件存储：http://www.qiniu.com/

**Comment by dofy** [comment]
遇到同样的问题
请求中 method 是 options
