### ISSUE TITLE
CommonJS 模块名称问题

### ISSUE THREAD

**Issue by luin** [mycolorway/simditor#183]
现在 simditor.js 里面引入依赖的方法是：
https://github.com/mycolorway/simditor/blob/master/lib/simditor.js#L15-L17
但是 "simple-module", "simple-hotkeys" 和 "simple-uploader" 这些模块并没有定义过，导致不能在 Browserify 环境下使用 simditor。

我现在的解决方法是设定 Browserify 的 require 路径为 editor/scripts，然后将 module.js/hotkeys.js/uploader.js 重命名为 simple-module.js/simple-hotkeys.js/simple-uploader.js 来完成引用。

为什么不在 require 时使用相对路径呢？或者如果每个模块相对独立，能不能把每个模块发布到 npm 上？

**Comment by farthinker** [comment]
@luin simple-module simple-hotkeys和simple-uploader这些组件会以相同的方式来定义commonJS的module，所以按道理只要引用了这些组件的js，相应的模块就会被定义（你可以参考一下其他组件的代码）。
commonJS模块的支持并没有经过太多的测试，欢迎更多的反馈

**Comment by luin** [comment]
@farthinker 明白了，因为我是从网站上下载的打包版本，所以没有发现原来每个模块都是独立的。那有个问题就是 simditor 的 package.json 里的 dependencies 并没有要依赖的3个模块，同样地 simple-uploader 依赖于 simple-module 但是也没有在 package.json 里面注明，这样的话安装起来没办法自动安装依赖。另外这几个包有发到哪个 commonjs 的包管器中吗？找了 npm 和 spm 都没有呢。

simditor 是我找到的最好用的编辑器了，棒棒哒！

**Comment by farthinker** [comment]
@luin CommonJS因为用的比较少，所以所以相关的东西做的不是很完善。你有时间帮忙修改一下package.json么，然后发布到npm，可以给我提交PR，不胜感激。
如果没有时间做也没有关系，后面我会抽时间来做。

**Comment by luin** [comment]
@farthinker 没问题呀~不过刚才发现 simple-module 在 npm 上被占用了，我等下给 NPM 发封邮件尝试申诉下吧。能发布到 npm 上的话用起来就方便多了

**Comment by luin** [comment]
Npm 回复说现有的 simple-module 符合模块规则，所以要发布到 npm 上最好要改个模块名。这样才可以让用户通过 npm 来安装

**Comment by farthinker** [comment]
@luin 用simple_module吧

**Comment by luin** [comment]
尝试改了一下，发现要变的地方不少，几乎每个库都要改，所以还是你直接操作会方便点

流程大概是：

1. 发布 simple-module
2. 对所有依赖 simple-module 的模块（比如 simple-hotkeys）执行 npm install --save simple_module，然后发布（看是否要全部统一成下划线的形式）
3. 不断循环过程 2，直到发布 simditor

**Comment by farthinker** [comment]
@luin node package已经发布到这里了：https://www.npmjs.com/package/simditor
