### ISSUE TITLE
能不能将工具栏图标的fontawesome换成iconfont以再减小体积

### ISSUE THREAD

**Issue by ydq** [mycolorway/simditor#184]
早些时候发现了simditor这个编辑器，很是喜欢。后来看了下，觉得fontawesome太大了，simditor中也仅仅只是用到了很少的一部分，而当前simditor中工具栏所用到的图标在iconfont中基本上都可以找得到，如果在iconfont中单独找出这些图标字体估计都不超过10K大小，然后再定制一下className不与用户的冲突我觉得会是一件很美好的事情。

**Comment by farthinker** [comment]
@ydq 暂时没有这个计划
