### ISSUE TITLE
simditor可以提供提取纯文本的方法吗

### ISSUE THREAD

**Issue by dannybaby** [mycolorway/simditor#185]
getValue()可以获取simditor中的HTML内容。
有没有提供提取纯文本的方法吗，去除HTML标签，返回纯文本内容。
多谢！

**Comment by farthinker** [comment]
@dannybaby 可以试试editor.formatter.clearHtml方法：
```
html = editor.getValue()
text = editor.formatter.clearHtml(html, true)
```
第二个参数指定是否保留换行
