### ISSUE TITLE
我的扩展　继承于时，　无法获得@editor.util函数

### ISSUE THREAD

**Issue by huyinghuan** [mycolorway/simditor#187]
由于无法获取函数调用　@editor.util.os.mac　,导致无法判断mac或其他绑定快捷键
https://github.com/huyinghuan/simditor-marked.

**Comment by huyinghuan** [comment]
继承Simditor.Button时，无法获取@editor.util对象．　　标题被github吞了

**Comment by farthinker** [comment]
@huyinghuan editor.util对象需要在simditor初始化完成之后才能获取，在_init方法里面应该是可以获取到@editor.util的

**Comment by huyinghuan** [comment]
Got it! 谢谢！　搞定了！
