### ISSUE TITLE
为什么我上传图片发布后 是一大串base64代码

### ISSUE THREAD

**Issue by gantoo** [mycolorway/simditor#192]
图片没有上传 变成base64代码存在数据库了 请问怎么解决?

响应应该没错吧
{"file_path":"54deee65a4775.jpg","msg":"ok uploading file","success":"true"}

**Comment by gantoo** [comment]
不知道怎么回事 我网上下个旧版的 js 替换了就可以了
最新版的不行,用了旧版的simditor-all.js marked.js simditor-marked.js 其他没改 成功了

**Comment by farthinker** [comment]
file_path应该是完整的图片地址
你在上传的过程中有什么报错么？

**Comment by gantoo** [comment]
@farthinker 完整地址也不行 没有报错
奇怪的是我从晚上找到旧的js 替换就可以了

**Comment by farthinker** [comment]
@gantoo  可能跟这个issue是相同的问题：https://github.com/mycolorway/simditor/issues/195

**Comment by gantoo** [comment]
@farthinker 就是说 要mime类型是json是吗 我有空试一试
谢了 新年快乐哈
