### ISSUE TITLE
editor.uploader.on('uploadsuccess'...中无法识别json

### ISSUE THREAD

**Issue by rainingmaster** [mycolorway/simditor#195]
在使用上传图片功能时无法识别返回的json内容，我查看代码，发现为什么在editor.uploader.on('uploaderror'中有$.parseJSON而editor.uploader.on('uploadsuccess'不用的？
在editor.uploader.on('uploadsuccess'不使用$.parseJSON时result.success等参数会出现undefined，result传入的好像只是个字符串？
我尝试在editor.uploader.on('uploadsuccess'中添加$.parseJSON解析字符串后能实现功能。

**Comment by farthinker** [comment]
@rainingmaster simple-uploader之前做过一个更新，把ajax的请求的dataType: json的去掉了，这样做是为了让upload的响应能够适用于更多的技术（例如rails的SJR）。这个更新之后simditor上传文件的接口可能需要做响应的调整，必须保证响应的mime类型是json，这样simditor在解析响应的时候才不会报错。

不过为了照顾一些粗心的同学，我在刚才的commit里面增加了自动parse json响应的功能。

**Comment by rainingmaster** [comment]
原来如此，在php设置header('Content-type: text/json');头就可以了。谢谢！
