### ISSUE TITLE
 源代码编辑切换在有<br>的情况下会重复生成<p></p>

### ISSUE THREAD

**Issue by hizhengfu** [mycolorway/simditor#201]
在源代码中输入类似这样的代码：

    <p>测试1</p>
    <p>123<br></p>
    <p>测试2</p>

切换就能重现

**Comment by farthinker** [comment]
https://github.com/mycolorway/simditor/commit/8cbd2a150fa13e1ad5b0fb4ce8260edfd5ab7a31
