### ISSUE TITLE
能否提供附件上传的按钮扩展？

### ISSUE THREAD

**Issue by youyi000** [mycolorway/simditor#203]
附件上传是一个基本功能，希望能够提供这个扩展。

**Comment by farthinker** [comment]
@youyi000 每个项目的附件上传逻辑都不一样，我觉得很难写出一个满足大多数项目需求的附件上传扩展。这个是Tower使用的附件上传扩展，你可以参考一下：https://gist.github.com/farthinker/7c831949c68cdbff9e5e

**Comment by youyi000** [comment]
@farthinker 谢了，给的网址一直打不开，比较奇怪。

**Comment by youyi000** [comment]
@farthinker 是不是必须得翻墙的？

**Comment by farthinker** [comment]
@youyi000 可能需要翻墙

**Comment by youyi000** [comment]
@farthinker 请问这个按钮怎么编译的，我按教程设置有问题？谢谢。

**Comment by guleng11** [comment]
您好，Tower使用的附件上传扩展可以重新给个链接吗，之前的链接打不开
