### ISSUE TITLE
期待加入显示 markdown源代码功能

### ISSUE THREAD

**Issue by qiutiaoming** [mycolorway/simditor#204]
你好，最近看到simditor已经更新了html显示源代码的功能，觉得非常好用。

可是，感觉使用markdown的人越来越多了，而现在大部分的`markdown`编辑采用的都是直接编辑markdown源代码的方式，然后通过预览的方式去调整markdown源代码（如`stackoverflow`,`segmentfault`等），这种方式极其不直接，远没有“所见即所得”的方式方便。

所以，能否直接添加一个按钮显示和编辑 markdown代码（如最后的那个html5的图标），这样可以将“所见即所得”，html5,markdown三种方式统一起来，用户可以根据自己的喜好去选择输入的方式。

**Comment by farthinker** [comment]
@qiutiaoming html to markdown的技术还不是很成熟，所以暂时没有让Simditor支持markdown编辑的计划
