### ISSUE TITLE
请问如何编译已经写好的按钮？

### ISSUE THREAD

**Issue by youyi000** [mycolorway/simditor#206]
请问如何编译已经写好的按钮？
根据教程设置，但是在grunt时总是报错，请问谁能详细介绍一下，这个按钮如何编译，谢谢。

**Comment by farthinker** [comment]
只需要把coffeescript文件编译成js，然后在项目里引用就可以了，没有特殊的编译过程

如果你的项目是一个rails项目，那么可以直接引用coffee文件，不需要编译

**Comment by youyi000** [comment]
3Ks @farthinker
