### ISSUE TITLE
网络贴图的问题

### ISSUE THREAD

**Issue by jhack77** [mycolorway/simditor#207]
1.网络贴图在firefox 下测试有问题，不会显示贴出的新图片，还是默认的图片。
2.网络贴图不会自动获取原图片的大小，是取默认图片的大小，这样图片容易变形。如果强制设定长与宽会发现是等比例调整，无法同时改变图片长与宽（除非手工去拖拉，但这样无法精确控制大小）。
3.能否禁掉网络传图，只保留本地上传？

**Comment by farthinker** [comment]
@jhack77 我这里测试是正常的：
![image](https://cloud.githubusercontent.com/assets/184323/6617801/853be224-c8f7-11e4-81f6-35b3e65497a4.png)

更提供更多的调试信息吗？比如操作系统、浏览器和重现的步骤

**Comment by jhack77** [comment]
收到的邮件不能直接回复，我发你GMAIL邮箱了。

**Comment by farthinker** [comment]
我暂时没有条件测试windows10 FF dev edition下的问题，我在Mac OSX 10.10.2 Firefox 34.0.5下测试的结果是：
![simditor-firefox-test](https://cloud.githubusercontent.com/assets/184323/6655343/15c309f8-cb37-11e4-9ddc-e43fcd42256d.gif)
没有出现你在邮件里所说的问题，希望有更多windows系统下的相关反馈

**Comment by jhack77** [comment]
输入图片地址后，不要立即回车，而是把光标焦点移动图片尺寸的文本框中。再点击回车。你看看效果。
