### ISSUE TITLE
how to set the alt of img?如何设置图片alt属性.

### ISSUE THREAD

**Issue by mlsjla** [mycolorway/simditor#209]
看了一下,默认上传后是:
<img alt="Image" class="selected" src="/static/s.png" data-image-size="120,120">

也就是图片alt属性是image

而服务器手册中返回的例子是:
{
  "success": true/false,
  "msg": "上传失败信息", # 可选
  "file_path": "[real file path]"
}

也就是说没有alt的配置项了?

**Comment by farthinker** [comment]
上传图片的alt默认会是图片的文件名（除非取不到文件名），外链图片暂时没有设置alt的功能

如果你上传的图片没有alt，需要更多调试信息来定位问题，比如你使用的操作系统和浏览器、如何重现问题

**Comment by mlsjla** [comment]
我用的是fedora(linux)64bit + chrome或者firefox 发现都是这样子....alt属性都是Image.....是否有配置参数?

**Comment by farthinker** [comment]
@mlsjla 我在mac firefox下面测试了一下，上传图片的alt是图片的文件名，外链图片的alt是Image（暂时不能设置alt），请确认一下你遇到的问题是图片上传成功之后alt不正确，还是外链图片的alt无法设置

**Comment by mlsjla** [comment]
很明确是。是上传图片。
点击上传本地图片那种。

我系统是linux  fedora21-64bit版本

**Comment by farthinker** [comment]
@mlsjla 抱歉，我暂时没有条件在linux fedora21-64bit版本下测试。如果方便的话能否在你的系统下面帮我调试一下，在`image.coffee`里面的如图位置增加一个log，然后看看输出的内容：
![image](https://cloud.githubusercontent.com/assets/184323/6795621/1af092c2-d21e-11e4-8fb9-79d44f15a7da.png)

**Comment by mlsjla** [comment]
@farthinker   问一下,image.coffee这个文件是哪个?
我用的版本js只有下面几个文件
hotkeys.js      jquery.min.js  module.min.js  simditor.min.js  uploader.min.js
hotkeys.min.js  module.js      simditor.js    uploader.js

您看一下是哪个文件.我是做后端的.前端不是很明了.

**Comment by farthinker** [comment]
稍后我给图片加一个修改alt属性的功能吧

**Comment by farthinker** [comment]
#218
