### ISSUE TITLE
官方演示可否展示本地上传图片功能

### ISSUE THREAD

**Issue by jhack77** [mycolorway/simditor#211]
我点击本地上传图片，选择图片后，没有任何反应。
upload: {
                    url:'/uploadImage',
                    params:null,
                    filekey:'imgFile',
                    connectionCount:5,
                    leaveConfirm:'正在上传文件，如果离开上传会自动取消'
                }

**Comment by lcjnil** [comment]
试试 http://simditor.tower.im/?upload ，本地grunt启动服务器之后也可以这样测试的

**Comment by farthinker** [comment]
@jhack77 http://simditor.tower.im上没有上传图片功能的演示，因为github pages不支持服务器端的脚本，以后我们可能将simditor的官网迁移到我们自己的服务器上，到时候会加上上传图片的演示

现在你只能把simditor的仓库clone到本地，然后按照教程搭建好开发环境，然后在http://localhost:3000/demo.html?upload 查看上传图片的演示
