### ISSUE TITLE
经测试图片本地上传不支持jquery 1.9.X版本。

### ISSUE THREAD

**Issue by jhack77** [mycolorway/simditor#212]
使用jquery 1.9 版本。点击本地上传图片。不会发送post请求。无法正常使用此功能

**Comment by farthinker** [comment]
@jhack77 抱歉，simditor只支持jQuery 2.0+，你可以尝试升级一下jQuery，然后用 https://github.com/jquery/jquery-migrate/ 解决兼容性问题
