### ISSUE TITLE
建议废弃使用closest

### ISSUE THREAD

**Issue by yuhengliang** [mycolorway/simditor#213]
.closest( selectors [, context ] )方法从 jQuery 1.7 开始，不再建议使用该方法，但是 jQuery 1.7 之前仍然可以使用。

**Comment by farthinker** [comment]
被废弃的方法是`.closest( selectors [, context ] )`，`.closest( selector )`并没有被废弃

不过simditor有个别地方使用了`.closest( selectors [, context ] )`，这种写法第二个参数会被忽略，我稍后会纠正这些错误

感谢你的提醒
