### ISSUE TITLE
左右缩进，能不能支持选择多行操作？

### ISSUE THREAD

**Issue by mancojiang** [mycolorway/simditor#216]

**Comment by farthinker** [comment]
@mancojiang 现在的缩进功能是对整个当前段落进行缩进操作，不知道你的需求具体是什么呢？在什么情况下进行怎么样的操作想达到什么期望?

**Comment by mancojiang** [comment]
如下图，选择了三行，然后点击向右缩进，能不能三行都有缩进的效果？
![qq20150327-2](https://cloud.githubusercontent.com/assets/4215281/6860465/6b496bbc-d463-11e4-8d68-6c5f57e3e9bf.png)
![qq20150327-3](https://cloud.githubusercontent.com/assets/4215281/6860467/6c02a136-d463-11e4-8741-7a9ae5faaa04.png)

**Comment by farthinker** [comment]
https://github.com/mycolorway/simditor/commit/8ba32b199d63d783e4c8a0c7e4cb22da8644674a
