### ISSUE TITLE
扩展按钮图标设置问题

### ISSUE THREAD

**Issue by huyinghuan** [mycolorway/simditor#219]
更新到2.1.5后发现　图标不显示了．　图标名称　官网没有指明具体使用哪一套图标命名规则
https://www.fonticons.com/fonts
在这里有多套图标．
另外是否　扩展按钮　是否还需额外在依赖fontawesome库？

**Comment by huyinghuan** [comment]
翻了一下simditor.css　发现里面没有额外的图标定义．．那么扩展按钮的icon这么填呢．．．

**Comment by farthinker** [comment]
@huyinghuan 目前simditor的工具栏icon的web font是通过base64格式引用的（直接编译到simditor.css里面）：
![image](https://cloud.githubusercontent.com/assets/184323/6913735/2389b01a-d7b6-11e4-93de-4061eba9786c.png)
目前的主流浏览器都是支持这种引用形式的，所以现在simditor不再需要引用单独的font文件，也不再需要依赖fontawesome

**Comment by huyinghuan** [comment]
@farthinker  那么扩展的按钮的图标按什么来命名？　我在simditor.css没有找到类似　
simditor-icon-compress之类的定义，　关于扩展的自定义图标css现在需要自己来写？simditor没有再提供全部图标样式了？
```
 class FullScreenButton extends Simditor.Button
    constructor: ->
      @isExpand = false
      super

    name: 'fullscreen'
    title: 'full-screen'
    icon: 'compress'
```

比如这样子无法显示图标．2.0.5版本是支持的．

所以问题我的问题是，　写自定义扩展时，如何设置自定义图标？

**Comment by farthinker** [comment]
@huyinghuan Simditor已经去掉了对fontawesome的依赖，第三方扩展的icon也不会添加到Simditor的默认样式里。所以如果有需要，第三方扩展需要自己维护对fontawesome的依赖（在扩展的bower.json里面加上fontawesome），或者改用图片作为icon，或者跟Simditor一样使用fonticons.com这样的工具来管理扩展的font icon（把font的base64数据写到扩展的css里面）

**Comment by huyinghuan** [comment]
这个是simiditor里面关于所有icon的定义　但是没有全部的，所以扩展按钮　无法使用　已定义css外的图标按钮了，写扩展按钮的话，现在的情况是需要自己来补充这个样式了，请问2.1.5是这个意思吗？
｀｀｀
.simditor-icon-bold:before {
  content: '\f001';
}

.simditor-icon-italic:before {
  content: '\f002';
}

.simditor-icon-underline:before {
  content: '\f003';
}

.simditor-icon-times:before {
  content: '\f004';
}

.simditor-icon-strikethrough:before {
  content: '\f005';
}

.simditor-icon-list-ol:before {
  content: '\f006';
}

.simditor-icon-list-ul:before {
  content: '\f007';
}

.simditor-icon-quote-left:before {
  content: '\f008';
}

.simditor-icon-table:before {
  content: '\f009';
}

.simditor-icon-link:before {
  content: '\f00a';
}

.simditor-icon-picture-o:before {
  content: '\f00b';
}

.simditor-icon-minus:before {
  content: '\f00c';
}

.simditor-icon-indent:before {
  content: '\f00d';
}

.simditor-icon-outdent:before {
  content: '\f00e';
}

.simditor-icon-chain-broken:before {
  content: '\f00f';
}

.simditor-icon-caret-down:before {
  content: '\f010';
}

.simditor-icon-caret-right:before {
  content: '\f011';
}

.simditor-icon-upload:before {
  content: '\f012';
}

.simditor-icon-undo:before {
  content: '\f013';
}

.simditor-icon-smile-o:before {
  content: '\f014';
}

.simditor-icon-tint:before {
  content: '\f015';
}

.simditor-icon-font:before {
  content: '\f016';
}

.simditor-icon-html5:before {
  content: '\f017';
}
｀｀｀

**Comment by huyinghuan** [comment]
谢谢！

**Comment by huyinghuan** [comment]
官方能否考虑一下　提供一个关于第三方扩展按钮的标准样式？，独立于现有的simditor.css（按需引用），便于第三方　扩展按钮统一风格．比如果第三方扩展的字体名字叫
```
Simditor-extension
```
