### ISSUE TITLE
[ＢＵＧ]　菜单按钮重复点击失效

### ISSUE THREAD

**Issue by huyinghuan** [mycolorway/simditor#221]
不断的重复点击菜单的按钮，　按钮失效
![20150331-105405_capture](https://cloud.githubusercontent.com/assets/3005433/6911527/5ee193f2-d794-11e4-97a0-de706e31173a.gif)

**Comment by farthinker** [comment]
@huyinghuan 没有能重现你所说的问题，能详细说明一下你遇到的问题么？
需要注意的是，大多数按钮需要编辑器处于focus状态的时候点击才会起作用

**Comment by huyinghuan** [comment]
额, 那么就没有问题了．　　我出现这个问题，是由于编辑器没有处于focuc状态，因为，我写了个全屏编辑的插件，自己测试的时候，发现反复点击按钮几次后，会出现按钮失效的情况．
