### ISSUE TITLE
Zepto 适配问题

### ISSUE THREAD

**Issue by yuanoook** [mycolorway/simditor#225]
超级棒的比编辑器，先赞一个

项目用 Zepto ，如何适配 simditor ? 想修改代码，不知有没有什么好思路

**Comment by farthinker** [comment]
@yuanoook 没有测试过Simditor与Zepto的兼容性，你可以把jquery换成zepto试试

**Comment by jiyinyiyong** [comment]
JQuery 体积过大, 我们也考虑用 Zepto, 目前打包的方式里插入的 jQuery, 我得看看怎么回事.

**Comment by jiyinyiyong** [comment]
试了一下, `$.merge` 方法报错, 查询了一下相关的方法, 一共用到了下面这些方法,
其中 zepto 当中没有对应实现的是:

```
proxy
merge
unique
isNumeric
makeArray
isNumeric
isArraycontains
```

包含对应实现的是:

```
isFunction
contains
extend
trim
isArray
inArray
parseJSON
```

看来是不可能迁移过去了.
