### ISSUE TITLE
关于阅读模式和编辑模式

### ISSUE THREAD

**Issue by yuanoook** [mycolorway/simditor#226]
在编辑模式的情况下，结果导出 html 格式化内容，放到其他地方去，反倒没有编辑模式里面样式好看。

可以做一个阅读模式部分，让编辑所得内容和最后看到的内容一致

**Comment by farthinker** [comment]
@yuanoook 你可以在显示html内容的容器上加上Simditor排版样式的class（.editor-style），这样编辑的样式就可以显示的样式一致了
