### ISSUE TITLE
官网demo中的table删除无效

### ISSUE THREAD

**Issue by xcchcaptain** [mycolorway/simditor#228]
在firefox 37.0.1下table的删除不起效果

**Comment by farthinker** [comment]
@xcchcaptain 我在mac firefox 37.0.1下测试表格是可以被正确删除了，有具体的问题重现步骤么
![image](https://cloud.githubusercontent.com/assets/184323/7222553/8e1e7c5c-e743-11e4-829d-b54c7545ffad.png)

**Comment by farthinker** [comment]
没有更多调试信息的话先close了
