### ISSUE TITLE
能否在js里获得一个editor的dom或jquery对象

### ISSUE THREAD

**Issue by Stardustwings** [mycolorway/simditor#232]
你好，我想达到的效果是，先在js里创建一个textarea的dom或jquery对象，然后把它初始化成一个editor的dom或jquery对象，然后根据需要动态地把这个editor对象添加到html里，不知能否做到呢？

**Comment by farthinker** [comment]
@Stardustwings 暂时没有这个功能哈，你可以在需要初始化simditor的地方，动态的append一个textarea，然后用这个textarea初始化editor
