### ISSUE TITLE
npm包引用simplemodule的问题

### ISSUE THREAD

**Issue by cy20006** [mycolorway/simditor#234]
lib/simditor.js 里面require('simple-module') 而 npm装的包名称叫 simplemodule，require('simditor')的时候会报错，提示找不到 simple-module 。  simple-hotkeys, simple-uploader 也是一样的

**Comment by farthinker** [comment]
@cy20006 只有simplemodule是没有短横杠的，因为npm上的simple-module已经被占用了，稍后我会在npm上发布一个新版本

**Comment by cy20006** [comment]
@farthinker 我指的是simple-hotkeys和simple-uploader 也 require了 simple-module ，也需要改一下吧？

**Comment by farthinker** [comment]
@cy20006 额，是的，我已经改了

**Comment by cy20006** [comment]
@farthinker 
![image](https://cloud.githubusercontent.com/assets/3981024/7404990/5f19d48c-ef1e-11e4-9e9d-19dba2b4313f.png)
昨天我打包的时候发现这块还有名称问题，这块是不是也需要跟下面一样啊？

**Comment by farthinker** [comment]
@cy20006 不能跟下面一行哈，因为非commonjs的加载方式，模块名就是simple-module，commonjs的名字那么奇葩是因为原名被占用了

**Comment by cy20006** [comment]
@farthinker ，嗯嗯，webpack把我坑了。。
