### ISSUE TITLE
toolbar使用px来确定长度的问题

### ISSUE THREAD

**Issue by Stardustwings** [mycolorway/simditor#235]
在使用中，我发现simditor的toolbar的宽度好像是根据初始化时浏览器窗口的宽度来决定的。但是，如果直接用px来确定toolbar的宽度的话，当浏览器窗口的宽度发生变化时toolbar的外观便会显得有点奇怪（因为toolbar的宽度并没有跟随浏览器窗口的宽度变化而变化），我想问问，有没有什么办法可以改为用百分比来确定toolbar的宽度吗？还有顺便好奇地问一下的事，使用px来确定toolbar的宽度是出于什么考虑呢？

**Comment by Stardustwings** [comment]
问题解决了，用chorme来查看toolbar的style时发现element.style的width覆盖了,把.simditor-toolbar里的width: 100%;改成width: 100% ! important; 即可，但这个问题应该不是因为跟我程序原来的样式冲突而产生，因为我直接运行demo也有同样的问题，个人觉得可能是在初始化simditor时浏览器给了toolbar这个元素一个默认的width，覆盖掉了原来.toolbar下的样式

**Comment by Stardustwings** [comment]
将toolbar的width改成100%后出现了另一个问题，placehoder的位置异常，会出现在toolbar里，暂时的解决方法是，
      $ '.simditor .simditor-wrapper .simditor-placeholder' .css 'top', '20%'
      $ '.simditor .simditor-wrapper .simditor-placeholder' .css 'top', ''

先给placeholder的top设一个值，然后再去掉，placeholder 的位置就正常了，具体原因我就不清楚了

**Comment by farthinker** [comment]
@Stardustwings Simditor的toolbar采用posotion fixed来实现浮动的效果。对于一个fixed定位的元素，如果不指定宽度，它的最大宽度只能是window的宽度，当编辑器宽度大于window宽度的时候，如果没有设置宽度，toolbar的大小就会出问题。

你遇到的问题是，window resize之后没有重新设置toolbar的宽度，我在上面commit已经修正了

**Comment by Stardustwings** [comment]
@farthinker toolbar的宽度问题是解决了，但placeholder出现了问题，它始终固定在一个位置，当toolbar的高度随着宽度变化而变化时，placeholder的位置始终不变，这使得它有时出现在正确的位置上，有时出现在toolbar里或别的地方

**Comment by farthinker** [comment]
@Stardustwings 你的toolbar里面的按钮是不是不止一行

**Comment by Stardustwings** [comment]
当窗口缩小时，按钮就不止一行了，而且我发现当toolbar有两行时，placeholder的位置才是正确的

**Comment by Stardustwings** [comment]
@farthinker 难道是这个插件的placeholder只考虑toolbar里只有一行按钮的情况吗？

**Comment by farthinker** [comment]
@Stardustwings 试一下最新的commit

**Comment by Stardustwings** [comment]
@farthinker ok! 问题解决，顺便给你回复解决问题的速度点个赞～
