### ISSUE TITLE
修改 code 的 HTML 输出，以兼容 markdown 标准

### ISSUE THREAD

**Issue by hustlzp** [mycolorway/simditor#237]
目前 Simditor 中 code 的 HTML 输出如下：

```html
<pre class="lang-python" data-lang="python">print('Hello')</pre>
```

而 [Markdown 标准](http://daringfireball.net/projects/markdown/syntax#precode) 中代码的 HTML 输出为：

```html
<pre><code>print('Hello')</code></pre>
```

能否修改 Simditor 中 code 的 HTML 输出，以兼容 markdown 标准？这样的话，Simditor 生成的 HTML 就可以和 markdown 代码无障碍转换了（比如采用 [to-markdown](https://github.com/domchristie/to-markdown) 来将 HTML 转换成 markdown，采用 [marked](https://github.com/chjj/marked) 将 markdown 转换成 HTML）。如下：

```html
<pre><code class="lang-python">print('Hello')</code></pre>
```

**Comment by farthinker** [comment]
@hustlzp 这个优化已经在计划中了，我正在构思一个simditor-mode扩展，整合源代码编辑和markdown编辑的功能，这个扩展会依赖to-markdown

**Comment by hustlzp** [comment]
Nice！期待整合版本~

我目前的项目就是需要这种整合版编辑器，不过现在只是把 Simditor 和一款 Markdown 编辑器简单做了下整合：[XEditor](https://github.com/hustlzp/XEditor)。

如果 Simditor 能够原声支持的话，再好不过！

**Comment by hustlzp** [comment]
在 fork 的 repo 中做了一个提交：

https://github.com/hustlzp/simditor/commit/859201b7b0c5cf12e498671e33005bad7f9f7dea

暂时实现了这种兼容。

**Comment by farthinker** [comment]
@hustlzp https://github.com/mycolorway/simditor/commit/a953aebac77263c62d1fd84ea2d83cbd4c444eed 最近就会合并

**Comment by farthinker** [comment]
试试[simditor-markdown](http://github.com/mycolorway/simditor-markdown)
