### ISSUE TITLE
能不能手动调用调整simditor排版的函数

### ISSUE THREAD

**Issue by Stardustwings** [mycolorway/simditor#238]
我在项目中使用多个simditor时会出现一个问题，除了第一个simditor能正常加载外，其余的toolbar都变成了竖排，就是排版出现了问题，然后调整一下浏览器窗口大小之后它们的排版就正常了，我大概看了一下代码，好像是调整窗口大小的时候会触发一个调整simditor排版的函数，然后我尝试使用window.dispatchEvent(new Event('resize'));
来手动触发窗口大小改变的事件，但似乎不起作用，请问，有没有提供手动调用调整simditor排版函数的接口，又或者是考虑一下在源码中加上在初始化完simditor之后先调用一次调整simditor排版的函数呢？我想这样或许能让simditor更好地整合到其它项目中～

**Comment by farthinker** [comment]
@Stardustwings 我这里测试一个页面加载多个Simditor没有出现你说的问题，麻烦你确认一下Simditor初始化的时候，相关的元素出于visible的状态，因为在隐藏状态下toolbar的大小和位置不能被正确的计算

**Comment by Stardustwings** [comment]
@farthinker 我用demo来测试的时候也没有出现这种情况，但是用在项目中的时候就会出这种问题，可能是项目中的某些做法跟simditor有冲突，但项目里的代码有点多，估计要等之后有空才能去搞明白它是怎么处理加进去的插件，另外我用把simditor的初始化放在setTimeout的方法里可以让simditor排版正常，但这样子似乎不好把握simditor初始化的时间，我感觉比较理想的的做法是手动动调用调整simditor排版的函数，又或是触发能跟该函数绑定的事件，请问能否做到呢？

**Comment by Stardustwings** [comment]
@farthinker 好像我把
window.dispatchEvent(new Event('resize'));
放在setTimeout的方法里也是可以解决问题的，应该是我那边项目的问题，这个issue就关了吧
