### ISSUE TITLE
jspm 无法载入依赖

### ISSUE THREAD

**Issue by alayii** [mycolorway/simditor#241]
由于没有入口文件，手动在 simditor@2.1.9 目录下添加 simditor@2.1.9.js 文件
`define(["github:mycolorway/simditor@2.1.9/scripts/simditor"], function(main) {
  return main;
});`

然后就会报错
`Uncaught Error: Unable to load dependency github:mycolorway/simditor@2.1.9/scripts/simditor.`

使用 module.exports 也是同样的，请问要如何解决呢？

**Comment by farthinker** [comment]
@alayii Simditor有在npm上发布，所以默认是兼容jspm的：
```
jspm init
jspm install npm:simditor
```
