### ISSUE TITLE
和http://bevacqua.github.io/rome/的js冲突了

### ISSUE THREAD

**Issue by amxku** [mycolorway/simditor#242]
和http://bevacqua.github.io/rome/的js冲突了

造成rome的时间选项下拉事件，无法选择

**Comment by farthinker** [comment]
@amxku 我测试了一下，没有发现任何冲突：
![image](https://cloud.githubusercontent.com/assets/184323/7553636/b1244c74-f736-11e4-8843-94de3df30e55.png)

以后提交issue的时候麻烦带上报错信息或者测试demo

**Comment by amxku** [comment]
![2015-05-11 08 46 35](https://cloud.githubusercontent.com/assets/674759/7556991/65a0f1ba-f7ba-11e4-8f82-2b3459358aff.png)
时间部分没法选择或滚动
