### ISSUE TITLE
有支持angularjs版本的simditor吗？

### ISSUE THREAD

**Issue by Cong5** [mycolorway/simditor#243]
有angularjs版本的吗？
把simditor封装directive来作为编辑器，但是发现source的功能无法使用了。点击查看源代码，是显示空白。

**Comment by farthinker** [comment]
@Cong5 暂时没有计划做angularjs的适配，但是好像有朋友做过这方面的尝试，你们可以交流交流：https://github.com/mycolorway/simditor/issues/217
关于source按钮，我近期准备将这个功能做成一个独立的扩展，这样可以把这个功能做的更稳定好用，又不影响核心功能的精简

**Comment by Cong5** [comment]
哦~~，好的。谢谢

**Comment by rockliuxn** [comment]
@Cong5  https://github.com/ghostboyzone/angular-simditor
这里有人封装了一个，可以参考一下！
