### ISSUE TITLE
下载了最新版本的simditor包。如果只想要最小size，是不是可以去掉simditor.css而只保留editor.scss？

### ISSUE THREAD

**Issue by chairy11** [mycolorway/simditor#244]
我在rails项目中使用simditor。
我只想保留最少的文件。

所以js我只保留了：
hotkeys.min.js
module.min.js
simditor.min.js
uploader.min.js。

但css方面，我想知道simditor.css是不是
editor.scss
fonticon.scss
simditor.scss
三者结合的结果？
可以删除simditor.css吗？

**Comment by farthinker** [comment]
@chairy11 simditor.css就是simditor.scss编译的结果，simditor.scss import了editor.scss和fonticon.scss

不过我建议你在rails项目中引用simditor.css而不是引用scss源文件，然后创建一个simditor-custom.scss来写项目相关的自定义样式，覆盖默认的simditor.css，这样upgrade的时候最方便。

另外，我们自己的rails项目里是使用bower来管理前端组件（包括Simditor）的。

**Comment by chairy11** [comment]
谢谢：）
