### ISSUE TITLE
pasteImage为true时支持什么场景呢?

### ISSUE THREAD

**Issue by zdjray** [mycolorway/simditor#245]
本地文件复制支持吗?
QQ中的图片复制支持吗?
Word文档可以直接把所有内容复制到输入框中吗?

**Comment by farthinker** [comment]
@zdjray 从本地文件夹里直接复制图片是不支持的，从word文档复制图片是可以的，用截图工具（比如QQ截图、或者Mac系统自带的截图）截图之后粘贴是支持的
