### ISSUE TITLE
可不可以支持embed标签？

### ISSUE THREAD

**Issue by dangcheng** [mycolorway/simditor#246]
我需要在编辑器中利用embed标签添加第三方网站的视频和第三方网站的音乐播放器，已经配置了allowedTags和allowedAttributes，但还是有以下问题:

1，在编辑器常规模式下直接插入embed代码时，里面的HTML标签直接被转换了，而且src被加上了链接。
2，在源代码编辑模式下，embed标签可以正常插入，切换回常规状态时，可以正常显示内容。但再次切换回源代码超级状态时，embed的闭合标签“</embed>”和连同后面的一个“</p>”标签直接就被去掉了。如果后面紧接着是一段文字，段落之前的“<p>”也会被去掉；如果后面是一个img标签，img标签的属性全都不见了，只剩下<img>。

不知贵团队是否可以增加对embed标签的支持，或者新增一个用来插入embed的按钮。

**Comment by farthinker** [comment]
我们会考虑增加一个simditor-media扩展，不过近期应该没有时间来做这个事情。

欢迎有兴趣的同学认领这个扩展，我可以提供设计方案方面的支持。

**Comment by zdjray** [comment]
同样也有这个需求,现在基本视频都是标配了,求大神扩展

**Comment by spirityy** [comment]
和quilljs同样 不支持视频  实在是遗憾 https://github.com/quilljs/quill/issues/203

**Comment by dangcheng** [comment]
#issue
