### ISSUE TITLE
FF下引用的问题

### ISSUE THREAD

**Issue by jkhaoqi110** [mycolorway/simditor#247]
输入字符后，ctrl+A全选后点引用按钮，会给body下的元素加上blockquote的父标签，官网首页的演示也会出现问题
chrome下无问题，FF 38.0.1出现问题

**Comment by farthinker** [comment]
@jkhaoqi110 默认行为就是这样的啊，而且chrome下面也是相同的行为，不明白你遇到的问题是什么

**Comment by jkhaoqi110** [comment]
chrome只是给富文本框内的内容增加blockquote，FF是给body增加
![4553543543](https://cloud.githubusercontent.com/assets/7346148/7752018/d151acb2-000f-11e5-81cd-4cee73a46990.gif)

**Comment by farthinker** [comment]
@jkhaoqi110 我在Mac Firefox 38.0.1下没有重现这个问题，你是在windows Firefox下遇到的这个问题么？麻烦提交问题的时候把相关环境和调试信息写清楚

**Comment by jkhaoqi110** [comment]
是的，windows 的 Firefox
