### ISSUE TITLE
能否添加居中功能

### ISSUE THREAD

**Issue by kutzhang** [mycolorway/simditor#249]
这个功能对我来说真的很重要，我也想写扩展，但是实在看不懂CoffeeScript。而且也看不懂你写的那些Button代码，我尝试过去写，但是行不通。

我非常喜欢你这款编辑器，真的想在项目中用它。能否为它加一个居中功能呢？

**Comment by ichord** [comment]
可以先搜索一下再提问，这个功能已经合并到 master 分支，待发布新版本： #240
