### ISSUE TITLE
升级2.1.10后还是在找simplemodule依赖

### ISSUE THREAD

**Issue by alayii** [mycolorway/simditor#252]
jspm config.js:

{
    "simditor": "npm:simditor@2.1.10",
     "npm:simditor@2.1.10": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "jquery": "npm:jquery@2.1.4",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "simple-hotkeys": "npm:simple-hotkeys@1.0.2",
      "simple-module": "npm:simple-module@2.0.6",
      "simple-uploader": "npm:simple-uploader@2.0.6"
    },
    "npm:simple-hotkeys@1.0.2": {
      "jquery": "npm:jquery@2.1.4",
      "simple-module": "npm:simple-module@2.0.6"
    },
    "npm:simple-module@2.0.6": {
      "jquery": "npm:jquery@2.1.4"
    },
    "npm:simple-uploader@2.0.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "jquery": "npm:jquery@2.1.4",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "simple-module": "npm:simple-module@2.0.6"
    }
}

simditor.js 里会有 `require('simplemodule')` 这行代码，但是改成simple-module后，依然会有依赖找不到的问题。

运行时会提示 simplemodule.js not found. 还有什么东西依赖了这个包吗？

**Comment by farthinker** [comment]
@alayii https://github.com/mycolorway/simditor/commit/6ace4a167e91382e075f22c361034028f59609f4

是我的疏忽，umd的配置没有更新，麻烦更新到2.1.11
