### ISSUE TITLE
如何隐藏工具栏但是具有工具栏功能能正常显示？？

### ISSUE THREAD

**Issue by isunmoon** [mycolorway/simditor#253]
![1](https://cloud.githubusercontent.com/assets/9160438/7764635/b7bf15a6-0086-11e5-9f63-41a379d50d87.png)
这是我的编辑界面，上传后在另一个页面，如何能使显示的页面隐藏工具栏后但是还能原样显示，隐藏工具栏后那个表格不能正常显示了。
![2](https://cloud.githubusercontent.com/assets/9160438/7764674/47391a88-0087-11e5-9391-091b346cc9e3.png)

**Comment by farthinker** [comment]
@isunmoon http://simditor.tower.im/docs/doc-config.html#anchor-toolbarHidden
