### ISSUE TITLE
如何build成一个文件

### ISSUE THREAD

**Issue by chenboxiang** [mycolorway/simditor#254]
目前下载的包里除了jquery外还有几个依赖的文件，如何打包成一个独立的文件？

**Comment by farthinker** [comment]
目前的release没有把依赖的文件打包到一起，因为考虑到一些依赖并不是必需的，而且现在的项目基本都有自己的前端资源打包策略，大家可以根据需要引用这些文件。
当然在release里增加一个simditor-all.js也不是不行，但是我个人别不是很推荐这种偷懒的引用方式。
