### ISSUE TITLE
As I type the words sometimes dissappea

### ISSUE THREAD

**Issue by sahanDissanayake** [mycolorway/simditor#255]
Hi, 

Sometimes the words disappear as I type, do not know why :cry: 

I would love to use this plugin, but not if there is a bug that is known

Thanks you so much

**Comment by farthinker** [comment]
Any more information to help me reproduce the bug? For example, OS info, browser info and specific words you typed.

**Comment by sahanDissanayake** [comment]
Mac OS - V 10.9.5
Google Chrome browser

just type sas sas sas as... faster and faster with pressing the space bar
Let me know how you get on

**Comment by farthinker** [comment]
Can not reproduce the bug in Google Chrome on Mac OS 10.10.3
