### ISSUE TITLE
关于对齐方式

### ISSUE THREAD

**Issue by cage1618** [mycolorway/simditor#263]
2.1.10版本添加那个对齐存在一个问题：
不是使用style="text-align:center" 而是 data-align="center" 这样的写法，
如果css可以自定义没有什么问题，可以在css中加属性选择器
但是，如果文章是发到第三方的平台上（如添加微信素材），没办法自己定义css，这个居中对齐或右对齐就失效了

**Comment by cage1618** [comment]
缩进也存在同样的问题

**Comment by cage1618** [comment]
这个问题没人理么

**Comment by cage1618** [comment]
这个问题没人理么

**Comment by farthinker** [comment]
最近暂时没有时间处理这个问题，后面可能会增加style属性的白名单过滤

**Comment by farthinker** [comment]
增加了行内样式的白名单过滤：https://github.com/mycolorway/simditor/pull/271
新版本发布之后就不会出现data-indent和data-align这样的属性了
