### ISSUE TITLE
火狐浏览器兼容性问题

### ISSUE THREAD

**Issue by LiangCY** [mycolorway/simditor#265]
在火狐浏览器中无法先选中文字然后修改样式，只能先选好样式再输入文字才有效果

**Comment by farthinker** [comment]
@LiangCY 具体是哪些按钮有问题呢？我在Mac Firefox 38.0.5上没有测试出类似的问题

麻烦提交Issue的时候附带详细一点的调试信息

**Comment by LiangCY** [comment]
我的是Windows的Firefox 38.0.6  ，在[http://simditor.tower.im/](http://simditor.tower.im/)这个网站上就有这样的问题，比如我要加粗一段文字，先选中了文字再点击按钮没有反应，只能先选好加粗，在输入文字才行

**Comment by farthinker** [comment]
@LiangCY 我使用windows 8 Firefox 38.0.5（已经是最新版本了）仍然不能重现问题，你使用的是开发者预览版的Firefox么？开发者预览版的浏览器不在Simditor的支持范围内。
