### ISSUE TITLE
fileKey 可否使用點操作？比如 data.filename

### ISSUE THREAD

**Issue by SolidZORO** [mycolorway/simditor#268]
我程序原先上傳接口是這樣：

```
"data": {
    "name": "05acf2065b667e22fdc344b513f497cd25d31df3_large_2x.jpg"
    "savename": "./Public/Uploads/Article/20150617/5580fa22a8d6f.jpg"
},
"info": "上传成功！",
"status": 1
```

fileKey我必然寫成 `data.savename`，不過並沒有生效。於是我按教程，加入`file_path`，變成這樣：

```
"data": {
    "name": "05acf2065b667e22fdc344b513f497cd25d31df3_large_2x.jpg"
    "savename": "./Public/Uploads/Article/20150617/5580fa22a8d6f.jpg"
},
"file_path": "./Public/Uploads/Article/20150617/5580fa22a8d6f.jpg",
"info": "上传成功！",
"status": 1
```

然後fileKey不寫，可以生效，但是只要我把`file_path`改成別的名字，並在配置裡寫上類似`"fileKey":"filexname"`，這樣，就沒效果了。

用的是最新 Simditor v2.1.13。

btw， 我發現 simditor.js 的日期是  2015-09-06，嚇到我了。現在才6月。

**Comment by farthinker** [comment]
@SolidZORO fileKey还不支持`data.savename`这样的值，你可能需要修改一下上传接口

2015-09-06是6月9日的意思……我稍后调整一下格式

**Comment by SolidZORO** [comment]
感謝回覆解決了疑問，那我另起新值就好。
