### ISSUE TITLE
合并单元格与i8n

### ISSUE THREAD

**Issue by suyu34** [mycolorway/simditor#269]
有考虑做合并表格的单元行的功能吗？i8n像静态属性一样挂SimpleModule在这个类函数上面，如果要切换国际化的话是怎么使用的？

**Comment by suyu34** [comment]
还有一个问题，就是i8n像静态熟悉一样挂SimpleModule在这个类函数上面，如果要切换国际化的话是怎么使用的？

**Comment by farthinker** [comment]
@suyu34 最近还没有增加合并单元格功能的计划。

可以这样设置SImditor的locale：
```
Simditor.locale = 'zh-CN'
```

**Comment by suyu34** [comment]
噢 好哒
