### ISSUE TITLE
关于 tour-usage 的问题

### ISSUE THREAD

**Issue by ifduyue** [mycolorway/simditor#274]
在 http://simditor.tower.im/tours/tour-usage.html

> 第一步：下载并引用

> 在这里下载并解压最新版的 Simditor 文件，然后在页面中引入这些文件：

> <link rel="stylesheet" type="text/css" href="[style path]/simditor.css" />

```javascript
  <script type="text/javascript" src="[script path]/jquery.min.js"></script>
  <script type="text/javascript" src="[script path]/module.js"></script>
  <script type="text/javascript" src="[script path]/hotkeys.js"></script>
  <script type="text/javascript" src="[script path]/uploader.js"></script>
  <script type="text/javascript" src="[script path]/simditor.js"></script>
```

如果我没有看错代码，lib/simditor.js 里面已经打包了 "simple-module","simple-hotkeys","simple-uploader"，没必要再引入一遍。而且 [bower.json](https://github.com/mycolorway/simditor/blob/master/bower.json#L37-L39) 里应该把 "simple-module","simple-hotkeys","simple-uploader" 设置为 devDependecies，而不是 dependencies，毕竟只是开发者打包的时候用到。

**Comment by farthinker** [comment]
@ifduyue simditor.js里面并没有打包依赖的脚本，bower.json里面simple-xxx的依赖并不是devDependencies

**Comment by ifduyue** [comment]
@farthinker 嗯，我看错了。 多谢。
