### ISSUE TITLE
allowedTags  、allowedAttributes 和  allowedStyles 反选

### ISSUE THREAD

**Issue by cage1618** [mycolorway/simditor#283]
这三个配置能不能提供反选功能，或者给个特定值表示所有

**Comment by farthinker** [comment]
现在 allowedTags/allowedAttributes/allowedStyles 这三个option里的值会附加到默认的白名单，而不是替换默认白名单

**Comment by pcxiong** [comment]
那请问，除了改代码之外，怎么实现替换，而不是附加

**Comment by NicoNicoNicoNico** [comment]
我并不需要过滤行内样式，去给每个标签添加allowedStyles太过赘余。希望能够提供反选或者某个值代表允许所有。
