### ISSUE TITLE
不兼容google mdl framework

### ISSUE THREAD

**Issue by HuaTiMeiTian** [mycolorway/simditor#285]
toolbar 按钮都点不动了

**Comment by farthinker** [comment]
I'll look into it

**Comment by farthinker** [comment]
经过测试并没有发现问题，能不能提供一个有问题的demo页面？

**Comment by HuaTiMeiTian** [comment]
你放到 布局的栅格里面了吗？我放进去后这个框架会有遮罩层 挡住工具栏，他们的遮罩层z-index好像是1

https://github.com/google/material-design-lite

**Comment by farthinker** [comment]
这个问题，你可以通过覆盖simditor的部分样式来解决呀，比如在simditor-custom.css里：
```
.mdl容器的class .simditor {
  z-index: 2;
}
```
这不是simditor本身的问题

**Comment by HuaTiMeiTian** [comment]
这个我肯定知道啊，别人就不行了，你们还是主动设置下吧
