### ISSUE TITLE
超链接 unlink button icon class的问题

### ISSUE THREAD

**Issue by Hubu** [mycolorway/simditor#289]
![49e7c0ab-b859-420b-83c7-0872bd239022](https://cloud.githubusercontent.com/assets/4191389/8922012/d1fe8178-350f-11e5-86fe-76d760357a95.png)
fa-chain-broken 可用 unlink无效

**Comment by farthinker** [comment]
这个问题已经解决了：https://github.com/mycolorway/simditor/commit/882d128659b3b9ac801e172d618c5264cfb66047
可能是网站没有更新
