### ISSUE TITLE
上传图片不能设置 多文件同时上传 ？

### ISSUE THREAD

**Issue by tamamadesu** [mycolorway/simditor#293]
js文件 createInput 里 加上 multiple："multiple" 后，是可以多选上传的，希望合到master上，应该没什么影响！

上传图片时候怎么加loading状态呢？上传图片后，不能通过鼠标拖动来控制图片大小吗，如果没有，我可以fork一份，看下怎么加上，因为现在的设置图片宽高，实用性太差了

**Comment by farthinker** [comment]
simditor默认会用mask来表示上传进度，你可以自己的custom样式里覆盖.simditor-image-loading和img.uploading的样式

拖拽改变图片尺寸的功能近期还没有计划，你有时间的话可以试试
