### ISSUE TITLE
设置textarea为required的时候An invalid form control with name='xxx' is not focusable.

### ISSUE THREAD

**Issue by BridgeEast** [mycolorway/simditor#295]

**Comment by farthinker** [comment]
出现问题的操作系统和浏览器是什么？有具体的重现步骤么？

我这边把textarea设置required attribute之后并没有出现错误

**Comment by farthinker** [comment]
出现这个问题的原因是chrome在提交表单之前会对required的textarea做验证，如果value是空，chrome就会尝试focus到textarea上，然后显示“Please fill out this field”错误信息。但是初始化Simditor之后，textarea处于隐藏状态，不能focus，所以chrome就报了这个错。

这个是浏览器的默认行为产生的冲突，并没有可行的解决方案，所以把textarea上的required属性去掉吧，然后自己编写表单的验证逻辑
