### ISSUE TITLE
很喜欢这个编辑器，但是不知道用PHP 怎么接受上传的图片

### ISSUE THREAD

**Issue by visvisvis** [mycolorway/simditor#297]
我现在用的PHP CI 框架，他自带的图片上传是表单提交的，然后传给PHP控制器，用$this->upload->do_upload('userfile')，上传处理的，userfile是input 的name。现在我用simditor,就不知道PHP应该怎么接收simditor上传过来的图片，不知道simditor具体该怎么配置。谢谢了，希望能得到回复！
要是有PHP的具体demo就好了，哈哈

**Comment by farthinker** [comment]
前端配置的文档参考一下这里：http://simditor.tower.im/docs/doc-config.html#anchor-upload

服务器端的文件参数名称是upload.fileKey（默认是upload_file），也就是你上面说的input的name
