### ISSUE TITLE
i18n 失效

### ISSUE THREAD

**Issue by wushaobo** [mycolorway/simditor#300]
发现自定义的 i18n和locale 无法在Simditor实例化时传入，国际化功能实际已失效了。
代码中关于i18n和locale的options的代码也被删除了一段时间了，这个功能放弃了么？

**Comment by wushaobo** [comment]
只好自己给Simditor加上 _t 这个方法，使用上自定义的i18n字典（比如在已有的zh-CN, en-US之外加上zh-TW）

    Simditor.prototype._t = (key) ->
        i18n[locale][key]

**Comment by farthinker** [comment]
@wushaobo i18n和locale不是在初始化的时候传入的，直接在Simditor上设置就可以了：
```
Simditor.i18n['zh-TW'] = ...

Simditor.locale = 'zh-TW'
```

**Comment by wushaobo** [comment]
@farthinker 玩法理解了，谢谢

**Comment by qqjt** [comment]
感觉把语言设置直接写在js里不太好……还是放在初始化时的配置项里好一些。
如果需要可切换语言的话，就得准备多份js了。
