### ISSUE TITLE
按钮弹出modal, modal 关闭并插入内容时，selection 报错

### ISSUE THREAD

**Issue by alayii** [mycolorway/simditor#302]
Uncaught IndexSizeError: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.   simditor.js:89

modal弹出之前的selection要做什么额外的操作让它保存起来吗。

我在编辑器 blur 时，保存了 window.getSelection() 和 range，然后插入内容，之前的版本可以工作，不知道要做什么修改与现在的版本兼容。

现在用的是 2.2.3

**Comment by farthinker** [comment]
你可以试试用`editor.focus()`方法来重新获取焦点，编辑器会自动恢复上一次blur的selection，然后再用`editor.selection.insertNode(node)`来插入内容

**Comment by alayii** [comment]
可以了，谢谢
