### ISSUE TITLE
有没有编写插件的文档呢？

### ISSUE THREAD

**Issue by dongli** [mycolorway/simditor#305]
我想在Simditor中使用MathJax来渲染数学公式，因此想要写个插件，但是我对如何编写Simditor插件一无所知，本人对Ruby非常熟悉，对JavaScript有些感觉。希望Simditor能够提供一些这方面的文档。谢谢！

**Comment by farthinker** [comment]
我稍后补上，感谢支持

**Comment by tamamadesu** [comment]
没文档  只能一直输出调试，还是有点麻烦的，希望可以补上，谢谢！！

**Comment by overtrue** [comment]
+1

**Comment by ihuguowei** [comment]
+1

**Comment by adoyle-h** [comment]
+1

**Comment by farthinker** [comment]
我会在下个大版本完善文档
