### ISSUE TITLE
编辑器的工具栏出不来？

### ISSUE THREAD

**Issue by tiandihai** [mycolorway/simditor#307]
按照你们的demo的步骤，一步一步 的弄的。
simditor.js的788行报错。“TypeError: simpleHotkeys is not a function”。
788行的代码如下： this.hotkeys = simpleHotkeys({
                                      el: this.editor.body
                                });。。。。
请问，没有找到simpleHotkeys()函数，是要依赖哪个文件吗？

**Comment by farthinker** [comment]
这些文件都引用了么：
```
<link rel="stylesheet" type="text/css" href="[style path]/simditor.css" />

<script type="text/javascript" src="[script path]/jquery.min.js"></script>
<script type="text/javascript" src="[script path]/module.js"></script>
<script type="text/javascript" src="[script path]/hotkeys.js"></script>
<script type="text/javascript" src="[script path]/uploader.js"></script>
<script type="text/javascript" src="[script path]/simditor.js"></script>
```

**Comment by tiandihai** [comment]
是的都引用了，我以为是版本问题，然后下载了其他的版本也是一样。我的代码如下：

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
	<link media="all" rel="stylesheet" type="text/css" href="styles/simditor.css" />

	<script type="text/javascript" src="scripts/jquery.min.js"></script>
	<script type="text/javascript" src="scripts/module.js"></script>
	<script type="text/javascript" src="scripts/uploader.js"></script>
	<script type="text/javascript" src="scripts/simditor.js"></script>
	<script type="text/javascript" src="scripts/hotKeys.js"></script>
	<script type="text/javascript">
		//window.onload = function(){
		//	var editor = new Simditor({
		//	   textarea: $('#editor')
		//	});
		//}

		$(function() {
			var editor = new Simditor({
			   textarea: $('#editor')
			});
		})
	</script>
	
</head>
<body>

	<textarea id="editor" placeholder="这里输入内容" autofocus>334</textarea>

</body>
</html>

**Comment by farthinker** [comment]
hotkey.js的引用要写在simditor前面

**Comment by tiandihai** [comment]
哦，soga，好了，可以了，谢谢了。
