### ISSUE TITLE
可以限制上传图片的大小吗？

### ISSUE THREAD

**Issue by alayii** [mycolorway/simditor#309]
或者上传之后回调函数

**Comment by alayii** [comment]
改了代码可以了，希望会有 API 可以使用。

**Comment by farthinker** [comment]
你可以绑定uploader的beforeupload事件：
```
editor.uploader.on 'beforeupload', (e, file) ->
  if file.size > 1024 *1024
    return false
```

**Comment by Creabine** [comment]
遇到了同样的问题，把具体位置贴出来方便以后的同学。
simditor.js文件中：

`this.editor.uploader.on('beforeupload', (function(_this) {
      return function(e, file) {
        //增加的
    	if( file.size > 512000 ){
    		alert('图片大小不能超过500Kb！');
    		return false;
    	}
        //增加的
        var $img;
        if (!file.inline) {
          return;
        }`

**Comment by Creabine** [comment]
遇到了同样的问题，把具体位置贴出来方便以后的同学。
simditor.js文件中：

`this.editor.uploader.on('beforeupload', (function(_this) {

      return function(e, file) {

    	if( file.size > 512000 ){

    		alert('图片大小不能超过500Kb！');

    		return false;

    	}

        var $img;

        if (!file.inline) {

          return;

        }
`
