### ISSUE TITLE
编辑器怎么赋值啊？

### ISSUE THREAD

**Issue by tiandihai** [mycolorway/simditor#311]
取值是直接$("#editor").val()就可以了。但是怎么赋值到编辑器里面呢？我用$("#editor").val("XXXXX")这样不行啊！！！！！

**Comment by farthinker** [comment]
http://simditor.tower.im/docs/doc-method.html#anchor-setValue

**Comment by tiandihai** [comment]
我草，这个文档我都没找到过，谢了，可以了。
