### ISSUE TITLE
上传图片后根据返回的图片调整尺寸

### ISSUE THREAD

**Issue by tanshiqi** [mycolorway/simditor#314]
目前使用的是七牛的服务，图片上传后加上尺寸缩放如imageView2/2/w/700, 但是编辑器里显示的width和height还是本地预览时候的大小，而不是根据服务器上传成功后获得的尺寸，之前2.1.15版本没有这个问题，更新到2.2后发现的，希望能解决。

**Comment by farthinker** [comment]
我想想办法，最近太忙，国庆的时候争取抽时间处理

**Comment by tanshiqi** [comment]
好的，感谢！
