### ISSUE TITLE
工具栏tips的显示延时在哪里改？显示延时太长

### ISSUE THREAD

**Issue by FlyingGarfield** [mycolorway/simditor#318]
在两个按钮之间移动的时候，tips都是即时显示，但是鼠标移到旁边，再次放在一个按钮上时，会延时1s左右才显示，没找到在源码哪个地方改😓    ಥ_ಥ

**Comment by farthinker** [comment]
按钮上的tooltip使用的是浏览器默认的，后面可能增加对simple-tooltip(https://github.com/mycolorway/simple-tooltip)的支持
