### ISSUE TITLE
两次点击插入代码按钮后编辑器内不会自动获取游标？

### ISSUE THREAD

**Issue by lulubai123** [mycolorway/simditor#319]
两次点击插入代码按钮后编辑器内不会自动获取游标，是本来就这样设计的嘛？

**Comment by farthinker** [comment]
是bug，最近有点忙很多issue都拖延了，国庆的时候抽时间处理一下

**Comment by lulubai123** [comment]
好的好的

**Comment by farthinker** [comment]
https://github.com/mycolorway/simditor/commit/d508023e7a76ca3ad3aca7151fe00460e66a6ae6
之前的这个commit已经修正了这个问题

**Comment by lulubai123** [comment]
ok
