### ISSUE TITLE
上传图片的两件事

### ISSUE THREAD

**Issue by QQ595332727** [mycolorway/simditor#320]
1. 除谷歌浏览器之外，其他浏览器上传成功的图片都无法直接在文本框内直接看到，而是要用鼠标点一下图片才显示出来。
2. 上传图片无法直观的看到进度，如果图片很多，也不知道什么时候上传完成了。
希望能有个进度条明确的显示出来图片的上传进度。

**Comment by QQ595332727** [comment]
补充一下，上面的表述一误。
除谷歌浏览器之外，其他浏览器上传成功的图片都无法直接在文本框内直接看到，而是要用鼠标点一下文本框的空白区域，图片才显示出来。

**Comment by QQ595332727** [comment]
除了谷歌浏览器之外，其他的似乎都是那样，IE、火狐、Edge以及360等。

**Comment by QQ595332727** [comment]
这是啥意思呢？

**Comment by farthinker** [comment]
@QQ595332727 我在Mac FF和win10 FF下测试都没有重现你所说的问题，麻烦你再确认一下是否是编辑器的问题

另外提供更详细的调试信息也会帮助我定位问题，比如操作系统版本、浏览器版本、Simditor版本、对应的出错信息以及重现步骤，如果有可以直接运行的demo是最好的
