### ISSUE TITLE
Simditor font 图标能否自行增加？

### ISSUE THREAD

**Issue by liyaodong** [mycolorway/simditor#324]
看过是 base64 的字体，旧版本中的 desktop 图标新版本也没了。想问问这个图标能否自定义或自己增加？

**Comment by farthinker** [comment]
官方的font icon库只会维护Simditor自己和一些优秀扩展的font icon，如果你写的扩展希望在官方font icon库里面增加图标，请先在这里提交你的扩展，审核通过之后我会在fonticon.scss里面增加你需要的图标

对于其他情况，我建议维护自己的font icon库，我目前使用的是Fonticons（https://www.fonticons.com/）的付费服务，你可以试试
