### ISSUE TITLE
希望能支持插入行内代码

### ISSUE THREAD

**Issue by zdhxiong** [mycolorway/simditor#325]
目前选中一个词，点工具栏的插入代码按钮，就会把这一行都加上`<pre><code></code></pre>`标签，而其实我只是想插入一个`<code></code>`标签，就像现在看到的这个`code`一样。

我比较常用的其他编辑器（ https://www.zybuluo.com/mdeditor  和 http://segmentfault.com ）的做法都是如果选中一行中的一部分，则把选中部分作为行内代码添加`<code></code>`；如果选中超过一行，则把选中部分添加`<pre><code></code></pre>`。希望 simditor 也能支持插入行内代码。

**Comment by farthinker** [comment]
这是个好建议，我会放到计划里

**Comment by xjpz** [comment]
好建议
