### ISSUE TITLE
simditor换行问题

### ISSUE THREAD

**Issue by supgeek-rod** [mycolorway/simditor#328]
关于换行有几个问题

1. 使用markdown扩展，在markdown模式下，如何设置回车即为换行(而不需要加3个空格)
2. 保存一个文本之后(内容为`<p>测试测<br>试测试<br>测试测试测试</p>`)，再次编辑它。在simditor中的内容没有保留换行。

**Comment by farthinker** [comment]
1. markdown模式下面的回车就是换行呀，不知道你具体遇到的是什么问题？
2. simditor是会正确输出br换行的，Tower里的br换行也能被正确保存，请你确认一下换行是不是在服务器端被过滤掉了

**Comment by supgeek-rod** [comment]
http://dev.3n1website.local/topic/44  可以在这里测试测试
1. markdown模式下，回车是不换行的，需要3个空格才行

**Comment by zdhxiong** [comment]
默认确实回车不换行, 不过`marked`有个参数可以开启回车换行. https://github.com/chjj/marked#breaks

**Comment by supgeek-rod** [comment]
非常感谢 @zdhxiong

**Comment by farthinker** [comment]
这个issue其实是simditor-markdown扩展的问题，以后请到扩展到仓库提交issue

simditor-markdown使用的是marked的默认配置，markdown的标准也是行尾两个空格回车才会换行，所以我不准备默认打开GFM line break的配置，有需要的同学请在自己的项目里修改marked的全局配置
