### ISSUE TITLE
超链接新窗口打开的问题

### ISSUE THREAD

**Issue by xjpz** [mycolorway/simditor#329]
请问什么时候增加超链接新窗口打开的功能呢？  目前只能当前窗口打开很多时候不方便。

**Comment by farthinker** [comment]
恩 我会放到计划中

**Comment by farthinker** [comment]
这个commit里增加了设置链接target的功能： https://github.com/mycolorway/simditor/commit/09f81d5619a769b6f3ba929da38e288c4b2c7636
暂时只支持_blank和_self，默认是_blank

**Comment by xjpz** [comment]
非常感谢你能采纳我的意见并实现这个功能。但是我发现文本说明似乎与实际功能是相反的，比如我选择文本说明为“在新窗口打开”的选项，但是实际却是在当前窗口打开，反之亦然。
