### ISSUE TITLE
复制/粘贴文本一直无效

### ISSUE THREAD

**Issue by skyblue** [mycolorway/simditor#330]
当初始值为空的时候, 粘贴文本无效, 但是如果已经有输入就可以

**Comment by farthinker** [comment]
粘贴不好用具体体现在哪里呢？

**Comment by skyblue** [comment]
粘贴网页文本一直报如上错误， 也可能复制的html标签未完整闭合，但是使用其他的编辑器的表现都还是可以的

**Comment by LiangCY** [comment]
2.3.1修复了
