### ISSUE TITLE
选择标题4之后，再选其他标题，class: active-h4没有remove

### ISSUE THREAD

**Issue by hooleez** [mycolorway/simditor#332]
标题5，选择之后，还是用的 p标签

v2.3.1

ps: 是否可以增加options自定义标题各数和字体大小呢？

**Comment by farthinker** [comment]
暂时没有计划自定义标题选项的个数，但是字体大小可以通过覆盖css来自定义

**Comment by hooleez** [comment]
你好，选择标题按钮是有bug的

点击标题4，再点击其他标题，比如标题3，那么这个按钮的class如下：
class="toolbar-item toolbar-item-title active-h4 active active-h3"

同时有了active-h4和active-h3

**Comment by farthinker** [comment]
上面reference那个commit修复了呀，会在v2.3.2里面发布，如果等不及可以先用master
