### ISSUE TITLE
关于图片上传的问题

### ISSUE THREAD

**Issue by VVendetta** [mycolorway/simditor#333]
我在使用simditor编辑器上传图片的时候，根据文档提示：
 
editor = new Simditor
 textarea: $('#editor')
 upload:
    url: ''
    params: null
    fileKey: 'upload_file'
    connectionCount: 3
leaveConfirm: 'Uploading is in progress, are you sure to leave this page?'
 
我想的是，那个url是ajax提交的地址，比如提交到我的一个文件上传类中，然后我自己写一个方法来处理（脚本语言是PHP）。但是我用开发者工具跟踪的时候，它请求的地址是我地址栏的地址，所以上传不成功。
不是很懂js与ajax，不知道如何解决问题。

**Comment by farthinker** [comment]
那个url就是服务器端的上传接口，如果留空默认就是当前页面的url

见你先学习一些前端开发的基础知识
