### ISSUE TITLE
图片上传后返回json数据的问题

### ISSUE THREAD

**Issue by VVendetta** [mycolorway/simditor#334]
额，再一次遇到问题，特来请教各位大神。文档说上传后返回一个json数据，如下：
{
  "success": true/false,
  "msg": "error message", # optional
  "file_path": "[real file path]"
}
我的代码：
//处理文件上传
    public function uploadFile(Request $request)
    {
        if ($file = $request->file('upload_file')) {

          $fileName = $file->getClientOriginalName();//获取文件原始名
          $extension = $file->getClientOriginalExtension() ?: 'png';//获取文件扩展名
          $folderName = '\upload';
          $destinationPath = public_path().$folderName;//文件保存路径
          $safeName = uniqid().'.'.$extension;
          $file->move($destinationPath, $safeName);
        }
        return response()->json(['file_path'=>public_path().'\upload']);
    }
public_path下面的upload文件夹是我上传文件的文件夹。

控制台提示的错误是：
Not allowed to load local resource: file:///F:/wamp/www/laravel/public/upload

我想请问的是，这个返回的文件路径是要http形式，还是绝对路径，还是我文件路径访问有权限（windows系统）
查到相关资料说：如果返回正确，图片信息中的base64 会替换成路径，可是我这里没有替换，前台显示的时候总是显示不出来

**Comment by farthinker** [comment]
file_path应该是图片的url，也就是http形式的，绝对路径和相对路径都可以。

base64没有替换，以及报错的原因都是因为通过json响应返回的file_path不能获取到图片

**Comment by VVendetta** [comment]
不论怎么修改都无法获取到图片。我修改了json返回的路径，现在是  http://localhost/laravel/upload
我用浏览器直接打开，可以访问到upload下面的资源，但是现在提示net::ERR_CONNECTION_REFUSED
我现在有点疑惑了，我测试返回一个完整的图片   如：http://localhost/laravel/upload/1.jpg，也无法获取到图片。

**Comment by farthinker** [comment]
你在地址栏里直接输入http://localhost/laravel/upload/1.jpg 可以访问到图片吗？如果不行就是图片路径有错或者服务器端的配置有些问题（比如没有开放静态资源的访问）

**Comment by VVendetta** [comment]
@farthinker   谢谢你的热心解答，已经找到了问题所在。返回的 json 路径是https，而本地环境访问是http，正在想办法解决。谢谢

**Comment by VVendetta** [comment]
@farthinker   现在路径问题已经解决了，图片上传也能传到指定目录，但是 那个base64 还是没有更改。前台文章无法读取到图片
