### ISSUE TITLE
插入代码时的Tab键问题

### ISSUE THREAD

**Issue by MiracleSnow** [mycolorway/simditor#335]
在插入代码时，按Tab键没有产生缩进，而是把焦点移到了其他地方

**Comment by farthinker** [comment]
我在http://simditor.tower.im/ 里测试，代码块里按tab是会正确插入两个空格的

如果你确认可以重现问题，请把系统版本、浏览器版本、simditor版本，报错信息或者重现步骤或者demo地址附上，否则我会关闭issue

**Comment by MiracleSnow** [comment]
在[http://simditor.tower.im/](http://simditor.tower.im/)测试没问题，但在tower编辑文档和周报时会有问题，不好意思

**Comment by farthinker** [comment]
好的，我帮你转到Tower组的工程师处理，感谢反馈
