### ISSUE TITLE
关于插入图片后显示的bug

### ISSUE THREAD

**Issue by VVendetta** [mycolorway/simditor#336]
昨天研究了一天，暂时确认图片上传成功后无法显示的问题是因为编辑器生成的img标签不完整。
如：
 <     img    src='*******'   ....没有结束标签   /> ,  而且图片后面要是跟着段落，不会显示出来。

**Comment by farthinker** [comment]
@VVendetta tower.im一直在使用simditor的图片上传功能，没有任何问题

**Comment by farthinker** [comment]
如果你确认可以重现问题，请把系统版本、浏览器版本、simditor版本，报错信息或者重现步骤或者demo地址附上，否则我会关闭issue

**Comment by VVendetta** [comment]
好的，稍等一下。我准备一下

**Comment by VVendetta** [comment]
@farthinker 你好，突然发现问题了。这个编辑器是不是太大就无法显示，我将图片压缩至40k左右就可以显示出来

**Comment by farthinker** [comment]
@VVendetta simditor没有做图片大小的限制，可能是那张图片的格式本身有问题，不能通过http请求获取
