### ISSUE TITLE
ideas to upload images and videos

### ISSUE THREAD

**Issue by MajidCS** [mycolorway/simditor#338]
I have some ideas for your editor

to upload images

![images](http://i.imgur.com/QV3ElvR.png)

edit image

![images](http://i.imgur.com/dLoxyOq.png)

to upload video

![images](http://i.imgur.com/FtN90ze.png)

if you paste link for video or image , the editor catch the links automatically

**Comment by farthinker** [comment]
Looks good, I'll have a try
