### ISSUE TITLE
IE9 下过大的图片会导致 simditor 超出页面边界

### ISSUE THREAD

**Issue by sonicwu** [mycolorway/simditor#339]
我们的产品一直在使用 simditor，但由于产品需支持“IE9+”，而不是 tower 和 simditor 的 “IE10+”，所以会有 IE9 下 simditor 中显示过大图片会导致编辑器超出边界的问题。

情况如下图，是否方便解决，多谢。

![simditor_ie9](http://i.imgur.com/MueUzou.png)

**Comment by farthinker** [comment]
抱歉，不会针对不支持的浏览器做维护

以后Simditor可能会彻底不支持IE，转而支持MS Edge

**Comment by gaboolic** [comment]
给img加个样式限制一下宽高应该就好了
