### ISSUE TITLE
初始化后，toolbar消失

### ISSUE THREAD

**Issue by csrgxtu** [mycolorway/simditor#344]
我在页面中初始化editor后，toolbar消失。
![screenshot from 2015-10-30 03 11 47](https://cloud.githubusercontent.com/assets/5053620/10840284/01676720-7eb4-11e5-933a-22cac43eec54.png)
btw， 我在页面中也使用了bootstrap，但是没有设置upload以前，就正常显示，配置了upload后就失败了。

**Comment by farthinker** [comment]
可能是跟bootstrap的样式冲突了，有可以调试的demo么？你自己在developer tool里看一下toolbar的样式呢，检查一下是什么冲突

**Comment by farthinker** [comment]
缺少调试或者报错信息，先关闭了
