### ISSUE TITLE
两次上传请求的问题

### ISSUE THREAD

**Issue by insub** [mycolorway/simditor#347]
Simditor很好用，感谢！

使用时发现上传时有两个问题，报告一下，另外还提两个建议
环境：
    Win7 - Chrome
    Mac - Chrome
    Simditor 版本： 2.3.4

按顺序加载了  module.min.js / hotkeys.min.js / uploader.js / simditor.min.js
上传到upyun form api，参数如下：
```javascript
var editor = new Simditor({
    textarea: $('#editor'),
    defaultImage: '/images/blank.jpg',
    toolbar: ['title','bold','italic','underline','strikethrough','color','ol','ul','blockquote','code','table','link','image','hr','indent','outdent'],
    upload: {
      url : 'http://v0.api.upyun.com/demo', //文件上传的接口地址
      params: {"policy":"<%= upyun_auth[:policy] %>","signature":"<%= upyun_auth[:sign] %>"}, //键值对,指定文件上传接口的额外参数,上传的时候随文件一起提交  
      host : "http://demo.b0.upaiyun.com/",
      fileKey: 'file', //服务器端获取文件数据的参数名  
      connectionCount: 3,
      leaveConfirm: '正在上传文件'
    },
    pasteImage: true
  });
```

issue A: 上传后需要点一下编辑器空白区域，才能显示出图片
issue B: 上传发出了两个请求，第一个的Request Method:OPTIONS ，无返回，第二个的Request Method:POST ， 上传成功

另外提两个建议，因为：qiniu和upyun等图片平台返回的参数都是固定格式，并且url是相对路径，建议
1. 是否可以允许定义返回参数名，而不是强制 “file_path” / “success” 参数等
2. 增加一个host参数，比如 "http://abc.xxx.com/", 用于拼接一个绝对地址的 file_path

**Comment by kazaff** [comment]
第一个请求（OPTIONS），应该是跨域造成的，不需要在意

**Comment by farthinker** [comment]
issue B不是bug，是跨域请求到正常现象
issue A我这边重现不了，环境是Mac Chrome：
![simditor-upload](https://cloud.githubusercontent.com/assets/184323/11201799/596a2004-8d1c-11e5-8d85-b93dd1e3d54e.gif)

**Comment by farthinker** [comment]
另外七牛的响应json是可以通过callback接口自定义的，所以暂时没有增加自定义响应参数的计划
