### ISSUE TITLE
启用markdown功能后editor.setValue('') 无法清除编辑框内容

### ISSUE THREAD

**Issue by asdio** [mycolorway/simditor#349]
v2.3.4 版本 
未启用markdown功能时候 setValue('') 可以清除内容，启用markdown之后就不行了，请教怎么解决？

**Comment by farthinker** [comment]
@asdio 在simditor-markdown v1.1.2里解决了这个问题：https://github.com/mycolorway/simditor-markdown/releases/tag/v1.1.2
