### ISSUE TITLE
插入代码没有排版

### ISSUE THREAD

**Issue by Dogzhou** [mycolorway/simditor#352]
插入格式化的代码提交后，再展示出来时所有代码都到一行去了

**Comment by farthinker** [comment]
需要给展示内容的容器增加class `editor-style`，比如：
```
<div class='article editor-style'>
  <!-- 这里是simditor产生的html -->
</div>
```

**Comment by Dogzhou** [comment]
非常感谢耐心指导，我按照您的方式做了，不知道是否是我理解错了，还是不行，比如这个页面`http://starzhou.com/blogs/simditor`，我应该在哪个 html 标签加 class `editor-style` 呢？还是我少引入了什么东西？

**Comment by farthinker** [comment]
@Dogzhou 如果想使用simditor默认的排版样式，你需要在页面上引用simditor.css，然后在段落容器上增加class`editor-style`
当然你也可以选择使用自定义的排版样式，注意你的代码标签需要包含这些样式：
```
pre {
    white-space: pre;
    word-wrap: normal;
    overflow-x: auto;
}
```

我看你提供的页面里使用了代码高亮，也请检查一下代码高亮的配置是否正确，另外还有一个可能是提交编辑器内容的时候，服务器端端接口把pre里面的`\n`换行符吃掉了

**Comment by Dogzhou** [comment]
@farthinker 问题解决了，原因是我之前使用的是 `ckeditor`，在 rails 里直接用的是 `f.cktext_area`，后来换 `simditor` 之后直接改成 `f.text_field` 了，input text 是单行的，不换行，所以换行符无效，换成 `f.text_area` 问题解决，多谢！
另：simditor 是我用过最好的富文本编辑器，牛逼！
