### ISSUE TITLE
粘贴内容会跑到编辑器的最下面

### ISSUE THREAD

**Issue by jkhaoqi110** [mycolorway/simditor#353]
每次 ctrl+v 都会跑到编辑器的最下面，最新的2.3.5也有这个问题

**Comment by oct16** [comment]
确实有，这个问题很严重。

**Comment by farthinker** [comment]
我这边测试没有问题，你们是在什么系统上使用什么浏览器遇到的这个问题？

**Comment by oct16** [comment]
我的是用mac 10.11.1 的chrome 46版本，用safari也有这个问题不过相对没有那么严重
粘贴的时候会闪一下，然后就直接跑到最下面了，有时候又会跑到最上面。

我测试了近期几个版本，貌似2.2--2.3.5之中很多都有这个问题，现在换成2.2.3到是正常了。

**Comment by farthinker** [comment]
这是我测试的过程，在Mac 10.11.1 chrome46下可以正常粘贴：

![simditor-paste](https://cloud.githubusercontent.com/assets/184323/11423657/3c20a042-9481-11e5-8d6a-596f057e42f1.gif)

**Comment by jkhaoqi110** [comment]
Windows8.1 Chrome 46 有问题
![image](https://cloud.githubusercontent.com/assets/7346148/11450209/a4bdfd70-95d0-11e5-8d8c-953cead237d1.png)
有时候粘贴速度快了下面这个还会直接跑出来

**Comment by beyonddevil** [comment]
跟上传图片一样，获取不到光标定位的位置，必须输入个空格或回车触发事件后，才会记录下当前的位置，否则都插入到最后了

**Comment by farthinker** [comment]
FIX: https://github.com/mycolorway/simditor/commit/adfef21f77c7f9a0a1870b23f61b9eb41804eb5e
