### ISSUE TITLE
上传图片，光标位置定位不准

### ISSUE THREAD

**Issue by beyonddevil** [mycolorway/simditor#359]
编辑过程中，每次内容改变会记录最后一次插入的信息。当直接将光标定位到之前的任意位置，想再次插入一张图，发现图片并未插入到光标定位到的位置，而仍然插入到了最后修改的地方 || 当首次实例化内容，因无最后编辑的位置，会将图片插入到最后

**Comment by beyonddevil** [comment]
@farthinker 我js水平太低了，我研究了挺长时间源码，真的是在一行一行研究，作者太牛了啊！起码在我这水平看来，比我高太多太多了，可能一辈子也达不到。。。

1.针对我提出的这个问题，我分析了下。光标重新定位了，但是输入内容是不受影响的，就在光标位置处正常插入，即使是emoji表情图片，也一样。问题是图片上传，出现了一个图片选择器，编辑器可能丢失了下焦点。然后先获取 最后一次记录的位置，没有获取到的话，就自动插入到末尾。
@farthinker 
2.是不是在点击图片上传的时候，重新来一个记录点，专门记录点击上传前的位置？？这样是不是能解决bug(还是纯粹我分析错误。。)

**Comment by farthinker** [comment]
FIX: https://github.com/mycolorway/simditor/commit/adfef21f77c7f9a0a1870b23f61b9eb41804eb5e
