### ISSUE TITLE
图片上传后，能否加入鼠标拖动图片边框，从而改变大小？

### ISSUE THREAD

**Issue by hiHitch** [mycolorway/simditor#362]
能否在图片上传之后，对图片进行拖动从而其改变它的大小，当前是点击图片之后就会弹出一个弹出层，然后手动输入宽度和高度，感觉蛮麻烦的。

**Comment by farthinker** [comment]
暂时不会增加拖拽改变图片大小的交互，不过我后续会完善图片编辑的弹出框
