### ISSUE TITLE
是否支持自定义toolbar的样式和功能呢？

### ISSUE THREAD

**Issue by icarusion** [mycolorway/simditor#364]
我想用自己的UI来控制toolbar，是否有API直接支持呢

**Comment by farthinker** [comment]
写custom style覆盖默认的样式实现不了么？

**Comment by icarusion** [comment]
@farthinker   另外，怎样把H1和H2单独剥离出来呢，不放在字号里？

**Comment by icarusion** [comment]
主要一个问题是，图片我想自己来做，但icon要放在那里，我看toolbar是js里生成的

**Comment by farthinker** [comment]
可以写css隐藏icon，然后用background-image代替

**Comment by icarusion** [comment]
好的，我先试试看。建议后续可以把UI剥离出来就牛逼了，比如https://github.com/quilljs/quill

**Comment by icarusion** [comment]
![image](https://cloud.githubusercontent.com/assets/5370542/11535369/89e2a45c-994e-11e5-8da6-de278d820b2e.png)

弄一晚上，样式终于调过来了。还差个图片上传，如果能提供一个methods，往当前光标位置插入一段html就好了！

**Comment by farthinker** [comment]
试试这个：
```
editor = new Simditor ...
editor.selection.insertNode node
```
