### ISSUE TITLE
能否根据图片的EXIF在上传图片前做图片的旋转呢？

### ISSUE THREAD

**Issue by happy-tao** [mycolorway/simditor#365]
最近碰到这么一个问题，在iOS的操作系统上，用户上传过图片之后，图片变的颠倒了。查了一下相关资料，应该是图片的exif的原因，能否根据图片的exif在图片上传前对图片做正确的旋转呢？

**Comment by icarusion** [comment]
Exif.js

http://code.ciaoca.com/javascript/exif-js/

**Comment by farthinker** [comment]
建议在服务器端做图片数据的处理
