### ISSUE TITLE
怎样过滤粘贴进来的文本样式呢？

### ISSUE THREAD

**Issue by icarusion** [mycolorway/simditor#366]
粘贴进来后，标签上多了很多style样式，怎样过滤这些css样式呢？

**Comment by farthinker** [comment]
Simditor在粘贴之后是会对粘贴内容做白名单过滤的，只会保留编辑器支持的标签和样式，你遇到具体问题是什么呢？什么样式你不想保留却没有被过滤？

**Comment by icarusion** [comment]
我粘贴进来，发现有<span style="color: xxx"></span>
span是可以有的，但是颜色不应该有呀！

**Comment by farthinker** [comment]
字体样式是SImditor支持的样式所以不会被过滤掉，我会考虑增加一个移除样式的按钮

**Comment by cestivan** [comment]
已经设置了 cleanPaste: true，参数都是生效的。但是复制到Simditor编辑器后还是出现很多样式：
```
<ul style="padding-left: 35px; color: rgb(102, 102, 102); font-family: STHeiti; font-size: medium; font-style: normal; font-weight: normal; line-height: 25.6px; background-color: rgb(255, 255, 255);">
  <li style="line-height: 2;">注册、登录</li>
</ul>
```
这是因为我的操作有问题么？

**Comment by feng99** [comment]
@cestivan 看看你的simditor版本是不是最新的^_^
