### ISSUE TITLE
能否提供选项,插入图片不上传,以Base64 DataURL方式存储

### ISSUE THREAD

**Issue by skyblue** [mycolorway/simditor#370]

**Comment by farthinker** [comment]
暂时不会增加这个选项

**Comment by skyblue** [comment]
当前在使用upload-plugin但上传失败的情况下就已经是base64方式插入了, 所以改动应该不会很大吧?

**Comment by skyblue** [comment]
当前在使用upload-plugin但上传失败的情况下就已经是base64方式插入了, 所以改动应该不会很大吧?
