### ISSUE TITLE
移动端样式不对

### ISSUE THREAD

**Issue by zhourongyu** [mycolorway/simditor#371]
simditor 有支持移动端模式吗？
使用 simditor 编辑后的文章在移动端看起来样式貌似不太对，width/height 这样的属性是一个绝对值。

**Comment by icarusion** [comment]
什么地方会用到width和height呢？

**Comment by zhourongyu** [comment]
图片的样式里面有
<img alt="Image" src="xxx" width="751" height="523">

**Comment by icarusion** [comment]
那就不知道了，你可以尝试把宽高过滤掉，然后100%宽，高度自适应。

**Comment by zhourongyu** [comment]
图片样式里面有, 类似这样
`<img alt="Image" src="xxx" width="751" height="523">`

**Comment by zhourongyu** [comment]
这么做是可行~  这个编辑器兼容下更好

**Comment by icarusion** [comment]
没办法，我也是在原基础上修改了很多，连图片上传我都是自己做的，没用他自带的，自带的好像有问题

**Comment by icarusion** [comment]
@zhourongyu 对了，你可以尝试判断如果是移动端，给img加css宽100%，高自适应，这样就可以忽略原先的数值了。用`!important`

**Comment by farthinker** [comment]
后面我会完善图片编辑的功能
