### ISSUE TITLE
235版本加载后工具栏样式不正确

### ISSUE THREAD

**Issue by yw9002** [mycolorway/simditor#372]
235版本加载后工具栏样式不正确。
环境：MAC PRO + chrome 46.0.2490.86 (64-bit)
本机测试时未加载任何除simditor需加载外的任何样式

<span class="simditor-icon simditor-icon-bold"></span>
.simditor .simditor-toolbar > ul > li > .toolbar-item中的line-heigh:40px会被覆盖，导致小图标垂直不能居中。

**Comment by farthinker** [comment]
麻烦你确认一下html里面有没有定义<!DOCTYPE html>
