### ISSUE TITLE
最新版插入图片, 基本上都不能插在光标处...

### ISSUE THREAD

**Issue by lincenying** [mycolorway/simditor#373]
最新版插入图片, 基本上都不能插在光标处...
用http://simditor.tower.im/?upload里的版本, 虽然偶尔也会出现, 但是几率非常小

测试方法, 拍一堆回车, 然后插入一张图片, 位置正常, 然后光标点到其他空行上, 再插入图片, 图片不会出现在新的光标位置, 而是出现在上一次插入的图片后面

**Comment by farthinker** [comment]
FIX: https://github.com/mycolorway/simditor/commit/adfef21f77c7f9a0a1870b23f61b9eb41804eb5e

**Comment by lincenying** [comment]
@farthinker 今天测试了下, 没这个问题了, 实在感谢...
