### ISSUE TITLE
建议把如何增加/切换语言写入文档。

### ISSUE THREAD

**Issue by linkdesu** [mycolorway/simditor#376]
我运气比较好，看了 Module.js 的说明，然后在 Simditor 的源码里搜索了一下才知道有中文以及如何设置。

建议还是把这个写在文档里比较好，比如 `通过设置 Simditor.locale = 'zh-CN' 来切换语言，默认支持 zh-CN, en-US 两种语言`

**Comment by farthinker** [comment]
收到，最近都没有太多时间维护这个项目，等有时间整理文档和网站的时候我会加上
