### ISSUE TITLE
想吐槽下图片为什么不能加链接？

### ISSUE THREAD

**Issue by linkdesu** [mycolorway/simditor#377]
团队因为比较欣赏这个编辑器的风格决定采用，结果真是太坑了，文档简陋不堪 :-1: ，源码也没什么注释 :-1: 。

最奇怪的是费劲千辛万苦加上了图片能够加超链的功能，然后却无法保存？！？！:angry: 最后的最后却发现凶手是核心代码中格式化 html 内容时刻意去除了 img 外的 a 标签。这个世界真是充满了深深的恶意~~ :joy: 

好了，吐槽完了还是要谢谢你们开发出了这款编辑器 :+1: ，经过这次填坑我也学习了很多。不过还是不明白为什么图片不然加超链？仅仅是因为这是你们的需求，还是因为设计上的缺陷，还是因为这有什么安全问题？

**Comment by lsqingfeng** [comment]
我想知道，我贴进去一段html代码，怎么预览效果？？？？急急急！！！

**Comment by farthinker** [comment]
编写这个编辑器的初衷是满足tower.im里评论和文档功能的需要，所以tower不需要的功能优先级都不高，图片加链接就属于这一类。最近半年都没有太多时间维护这个项目，这类优先级不高的功能暂时没有时间来做，抱歉。
