### ISSUE TITLE
怎么预览html样式

### ISSUE THREAD

**Issue by lsqingfeng** [mycolorway/simditor#378]
我贴进去一段html代码，怎么预览他的效果？？？求解

**Comment by farthinker** [comment]
想直接编辑html代码可以试试simditor-html扩展：https://github.com/mycolorway/simditor-html

**Comment by lsqingfeng** [comment]
为什么 会报
Uncaught IndexSizeError: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index. 这个问题
