### ISSUE TITLE
有个文案错误

### ISSUE THREAD

**Issue by yuanjianhang** [mycolorway/simditor#383]
是个小问题。还是给你们反馈下：
i18n.coffee里面：
`
'openLinkInCurrentWindow': '在新窗口中打开'
'openLinkInNewWindow': '在当前窗口中打开'
`
应该改为：
`
'openLinkInCurrentWindow': '在当前窗口中打开'
'openLinkInNewWindow': '在新窗口中打开'
`

**Comment by tinyfive** [comment]
已经在 #393 修正。欢迎直接给我们提 PR ; )
