### ISSUE TITLE
关于图片上传成功后图片显示的问题

### ISSUE THREAD

**Issue by visvisvis** [mycolorway/simditor#384]
我前几天下载了这个编辑器（很好看），我也成功的实现了图片上传的功能，但是碰到一个问题：
【上传成功后图片不会立马出现，必须要点击下编辑器<teatarea>的任意地方，图片才能出现】
我观察图片上传后光标消失了，是不是因为这个原因才要点击一下图片才出现呢？不过点一下后图片也正常出现在了上传前光标出现的地方。请问这个问题要怎么解决呢？

**Comment by visvisvis** [comment]
我测试了下，360，火狐浏览器上传后可以马上出现，但是百度浏览器不行，还是得点击下编辑区域

**Comment by farthinker** [comment]
百度浏览器的chrome内核版本比较低，不在支持范围内，抱歉
