### ISSUE TITLE
关于粘贴行为不自动清除code块内的br标签

### ISSUE THREAD

**Issue by ouerlianchuang** [mycolorway/simditor#386]
simditor-icon-code 点击 生成的\<pre\>标签 内 默认会拥有一个\<br\>标签  
![image](https://cloud.githubusercontent.com/assets/10338335/12060573/fa9888cc-afad-11e5-994b-909daaced735.png)
在\<pre\>内敲击输入代码输入会自动清除掉\<br\>
![image](https://cloud.githubusercontent.com/assets/10338335/12060658/60450a00-afaf-11e5-89cc-c7e3a09c5880.png)

但是直接在pr标签内粘贴内容却不会清除\<br\>，且之后的同行内输入也不会清除掉br
![image](https://cloud.githubusercontent.com/assets/10338335/12060632/d649509a-afae-11e5-8062-6f8c8afde504.png)

**Comment by ouerlianchuang** [comment]
其他地方粘贴内容也不会清除br标签

**Comment by farthinker** [comment]
下个大版本会尝试解决这个问题

**Comment by iwege** [comment]
@farthinker 这个问题已经解决么？目前单内容会有多个br保留..
