### ISSUE TITLE
如何动态的追加内容呢？

### ISSUE THREAD

**Issue by clopopo** [mycolorway/simditor#388]
你好，我看了一下api，setValue 只是替换所有内容，我想在光标处添加内容，怎么才能实现呢

**Comment by lincenying** [comment]
编辑器.selection.insertNode(.........);

**Comment by clopopo** [comment]
我调用这个接口添加内容，半天才显示出来，难道有延时？

**Comment by Tony1952466760** [comment]
editor.focus();
editor.selection.range().insertNode($("<ul></ul>"));
这样的方法报错

**Comment by lincenying** [comment]
editors.focus();
var $img = '<img src="1.jpg" />';
editors.selection.insertNode($img);
