### ISSUE TITLE
关于编辑器XSS安全问题

### ISSUE THREAD

**Issue by eyson** [mycolorway/simditor#391]
编辑器设计的时候是有考虑这方面的问题的，但细节做得不够。
比如我添加一个连接的时候，在输入URL的地方填写`http://xxx.xxx.com/" onclick="alert(1)`
目前看安全风险比较大，请及时修复。

**Comment by farthinker** [comment]
我这里测试没有重现链接href属性的xss漏洞，href的内容会被正确转义：
```
<a href="http://xxx.xxx.com/%22%20onclick=%22alert(1)" target="_blank">链接文字</a>
```
能不能详细说一下重现XSS漏洞的步骤？

**Comment by eyson** [comment]
![image](https://cloud.githubusercontent.com/assets/1028681/12198431/baae95f0-b64a-11e5-8741-fabce515f1f1.png)

在设置超链接的地方试试这行代码
`http://javascript:alert(1);'" onclick="alert(1);"`

**Comment by eyson** [comment]
在tower的官网上是无法重现的，我们在使用的过程中是可以重现的。不知道tower是否有做其它的特殊处理？
