### ISSUE TITLE
和AmazeUI样式冲突

### ISSUE THREAD

**Issue by Kenshinhu** [mycolorway/simditor#398]
如果在有使用 AmazeUI 的情况下,在 class="form"下的的textarea会有部分样式不正常

**Comment by Kenshinhu** [comment]
![Uploading Screen Shot 2016-01-13 at 1.55.45 PM.png…]()

**Comment by Kenshinhu** [comment]
![Uploading Screen Shot 2016-01-13 at 1.55.53 PM.png…]()
![Uploading Screen Shot 2016-01-13 at 1.55.53 PM.png…]()

**Comment by Kenshinhu** [comment]
![screen shot 2016-01-13 at 1 55 53 pm](https://cloud.githubusercontent.com/assets/4474680/12286330/1b267342-b9fe-11e5-92aa-e16ba75a0d12.png)

**Comment by farthinker** [comment]
在下个大版本会考虑解决这个问题
