### ISSUE TITLE
是否可以配置图片操作时候的工具框显示或者不显示

### ISSUE THREAD

**Issue by KevinPan** [mycolorway/simditor#399]
这个图片操作的工具框能否配置显示或者不显示（当图片在选中状态是会mo'ren默认出现）
或者只显示Size，Alt，Url中的部分，因为我显示是将url在服务器转成Base64的方式（免得存储文件），所以当我点击图片出现这个工具框的时候显示的Url可能就会是很大的字符串，而且用户也不需要操作这个Url，浏览器也可能会卡死。谢谢~~~

![untitled](https://cloud.githubusercontent.com/assets/1612571/12303751/076ab4d0-ba67-11e5-8393-9769bc8b280c.png)

**Comment by Kenshinhu** [comment]
想问问你也有遇到过图片超出编辑 框的问题吗?

**Comment by KevinPan** [comment]
@Kenshinhu 图片过大的时候会

**Comment by farthinker** [comment]
不推荐保存图片的base64数据
