### ISSUE TITLE
upload 中能否增加一个callback

### ISSUE THREAD

**Issue by KevinPan** [mycolorway/simditor#400]
现在upload图片的时候，如果服务器返回错误信息，默认是使用alert将msg显示出来，是否可以在upload定义一个error的callback，这样就可以自定义错误消息的显示方式了。
![untitled](https://cloud.githubusercontent.com/assets/1612571/12318162/23e7562e-bad3-11e5-87b5-3b1f3fe03a22.png)

**Comment by farthinker** [comment]
```
editor.uploader.on 'uploaderror', (file, xhr, status) ->
  # handle error
```
