### ISSUE TITLE
firefox浏览器, 从word里复制文档时, 会有样式插入

### ISSUE THREAD

**Issue by lincenying** [mycolorway/simditor#401]
firefox浏览器, 从word里复制文档时, 会有样式插入

http://dev.zdimg.com/temp/20160120/1b4dcb1ee6a50f1654bb7fd05358431d.png@1e_561w_1c_0i_0o_100Q_1x.png

**Comment by lincenying** [comment]
mac系统

**Comment by tudousi** [comment]
@lincenying 或者你可以先复制到记事本里，在复制到编辑器里面
