### ISSUE TITLE
关于存储MD还是HTML的疑惑

### ISSUE THREAD

**Issue by qiujuer** [mycolorway/simditor#404]
其实有时候我就在想存储到数据库的时候究竟是存储HTML好还是MD文档好，如果存储HTML好处就是渲染方便，但是存储和可编辑性相对较弱，而MD的编辑性是比HTML更强的，存储起来也更佳节约空间，缺点就是显示的时候需要使用js进行转换渲染。

大家对这个有没有好的看法？最近重构项目的时候心里一直有些矛盾。

**Comment by virusdefender** [comment]
我一般都是 MD 和 HTML 同时存的，编辑用 MD，HTML 避免重复渲染。

**Comment by qiujuer** [comment]
同时存储？这个代价有些高。另外感觉simditor，编辑MD的时候又些粗糙，感觉和之前的功能很不协调，之前的都比较精致，但是MD编辑却感觉是随意加上的一样。希望作者能够再打磨打磨。
