### ISSUE TITLE
如何新增自定义class

### ISSUE THREAD

**Issue by zhourongyu** [mycolorway/simditor#407]
做了一些自定义改造，比如新增 link 的时候添加 class="link", 但是提交后却消失了

**Comment by tinyfive** [comment]
编辑器的内容都会通过 src/formatter 模块进行格式化，默认配置中并不允许链接的 class 属性 @zhourongyu

**Comment by farthinker** [comment]
你可以尝试修改过滤掉白名单配置：http://simditor.tower.im/docs/doc-config.html#anchor-allowedAttributes
