### ISSUE TITLE
图片上传时，图片太大会超出编辑器。

### ISSUE THREAD

**Issue by linjiaju8** [mycolorway/simditor#411]
在使用图片上传时遇到图片太大会超出编辑器的问题，应该做成出现横竖滚动条，或自动压缩图片大小。如图：
![20160224161138](https://cloud.githubusercontent.com/assets/6505182/13279262/6a2ea660-db11-11e5-8f6b-4c8e8cd58bb8.png)

**Comment by ydq** [comment]
可以自己在外部定义一个样式 让所有的图片 max-width 最大等于容器的 100% 即可。

**Comment by frantic1048** [comment]
@ydq 这样会导致实际尺寸和显示出来的尺寸不符，还有比例失真的问题诶 ~(>_<~)
如果 simditor 提供个设置默认图片尺寸的选项什么的就好了(っ- ‸ – ς)

**Comment by farthinker** [comment]
只设置max-width比例是不会失真的，这其实是一个设计取舍的问题，下个版本给考虑自动设置max-width
