### ISSUE TITLE
替换粘贴时，粘贴的内容会粘贴到顶部

### ISSUE THREAD

**Issue by xiaojimao18** [mycolorway/simditor#415]
复制一段文字，再选中一段文字，直接替换粘贴，有时粘贴的内容会直接粘贴到顶部。

系统 OSX 10.10.5
浏览器 Chrome 48

**Comment by farthinker** [comment]
不能重现问题

**Comment by xiaojimao18** [comment]
官方首页的编辑器中，选中“Supported Browsers: IE10+、Chrome、Firefox、Safari.”这一段，复制并粘贴，粘贴的内容回到顶部
