### ISSUE TITLE
替换粘贴时，粘贴的内容会粘贴到顶部

### ISSUE THREAD

**Issue by xiaojimao18** [mycolorway/simditor#419]
首页(http://simditor.tower.im/)的编辑器中，选中“Supported Browsers: IE10+、Chrome、Firefox、Safari.”这一段，复制并粘贴，粘贴的内容会粘贴到顶部

系统 OSX 10.10.5
浏览器 Chrome 48

**Comment by zzjin** [comment]
same error here using editor at tower.im
