### ISSUE TITLE
代码编辑功能 command+方向键 光标位置变化出错

### ISSUE THREAD

**Issue by heziqiang** [mycolorway/simditor#420]
重现：（firefox浏览器）
1. 按“</>”插入代码
2. 输入“12”，现在游标在 `2` 后面
3. 键盘按“←”(Left)一下，现在游标在 `1` 和 `2` 之间
4. 键盘按“⌘→”(Cmd+Right)移到行末，现在游标应在 `2` 后面
5. 键盘按“↩”(Return)插入新行
期望在“2”后面回车， 结果却在 `1` 和 `2` 之间回车。
备注：chrome下正常

**Comment by ziqianghe** [comment]
Hi, 这个问题有计划处理吗？
