### ISSUE TITLE
关于编辑的时候，<pre><code>内代码被转换成HTML的问题

### ISSUE THREAD

**Issue by ysk2014** [mycolorway/simditor#422]
前面看过有人提过这个问题，但是并没有解决啊。我用的是2.3.6的版本还是出现这个问题
`<textarea id="editor" placeholder="Balabala" autofocus><pre><code class="lang-css">&nbsp;&lt;link rel="stylesheet" type="text/css" href="../bin/css/nanoscroller.css"&gt;<br></code></pre></textarea>`

**Comment by jianghejie** [comment]
同遇到这个问题，但是感觉simditor团队对于解决问题的积极性不高。需要说明的是simditor确实是一个很优秀的编辑器，不过bug略多。
