### ISSUE TITLE
能否提供一个图片上传而不是图片链接的操作按钮

### ISSUE THREAD

**Issue by gengyangabc123** [mycolorway/simditor#424]
如题：能否提供一个图片上传而不是图片链接的操作按钮

一直想找一款支持手机端浏览的富文本，simditor有些接近，希望官方能继续朝着兼容手机端的方向开发，另外图片上传功能最好能有，谢谢！

**Comment by duzhipeng** [comment]
> 如题：能否提供一个图片上传而不是图片链接的操作按钮
> 
> 一直想找一款支持手机端浏览的富文本，simditor有些接近，希望官方能继续朝着兼容手机端的方向开发，另外图片上传功能最好能有，谢谢！

同学不仔细看文档啊，图片上传的功能一直都有：http://simditor.tower.im/docs/doc-config.html#anchor-upload

**Comment by zhouseahe** [comment]
@duzhipeng   上传图片的回调函数 在哪里呢？

**Comment by duzhipeng** [comment]
> @duzhipeng 上传图片的回调函数 在哪里呢？

1. simditor有几个依赖，如果用NPM安装，会自动安装3个依赖，如果直接下载ZIP包安装的，默认带了这3个依赖。这3个依赖其中一个是负责上传图片的upload方法。
2. 按照文档，你实例化simditor的时候定义好upload的一些参数，包括后端接收图片数据的接口等，upload方法会按照你定义的接口传递数据，你的接口在接收到图片数据，并处理好存储逻辑后，返回一个JSON给simditor就行了。

文档这部分的链接我上面一个回复也给了，看不懂我就是在没办法了。

**Comment by zhouseahe** [comment]
```
editor.uploader.on("uploadcomplete", function(e, file, result){
 Pace.stop();
  $.unblockUI();
});
```

**Comment by duzhipeng** [comment]
> editor.uploader.on("uploadcomplete", function(e, file, result){
>  Pace.stop();
>   $.unblockUI();
> });

https://github.com/mycolorway/simple-uploader

**Comment by zhouseahe** [comment]
@duzhipeng  ， 为什么 #308 加高度的方式 ， 我用了后高度没有变化呢

**Comment by paxst** [comment]
你返回一个JSON,那前端怎么获取得到呢。在upload参数里没有相应的回调啊。比如前端需要对图片名称做一些处理。

**Comment by xueyuchen** [comment]
@duzhipeng 
simple-uploader配合阿里云OSS有问题  能把图片上传的操作权限扩大些吗

**Comment by duzhipeng** [comment]
> simple-uploader配合阿里云OSS有问题 能把图片上传的操作权限扩大些吗

我不是这个项目的开发者。。。。
