### ISSUE TITLE
在IE9上會有光標遺失和內容跑出輸入框外的問題

### ISSUE THREAD

**Issue by Nkeys** [mycolorway/simditor#426]
如題 在IE9上, 輸入框內的光標會遺失, 輸入內容的位置也會跑偏
這個問題有辦法解決嗎？
感恩

**Comment by ydq** [comment]
Supported Browsers: IE10+、Chrome、Firefox、Safari.

**Comment by RuochenLyu** [comment]
`Supported Browsers: IE10+、Chrome、Firefox、Safari.`
