### ISSUE TITLE
上传图片后的回调函数如何写

### ISSUE THREAD

**Issue by zhouseahe** [mycolorway/simditor#427]
文档中没有看到 谢谢

**Comment by paxst** [comment]
表示我也没有找到。。。同求

**Comment by shushu-hanfula** [comment]
同求啊

**Comment by shushu-hanfula** [comment]
在源代码里翻出了这么个注释：
 JSON response after uploading complete:

    ```coffee
    {
      "success": true/false,
      "msg": "error message", # optional
      "file_path": "[real file path]"
    }
    ```
位于文件simditor/site/_data/configs.yml 107行

**Comment by RuochenLyu** [comment]
[搜索](https://github.com/mycolorway/simditor/search?q=%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87&type=Issues&utf8=%E2%9C%93)
