### ISSUE TITLE
编辑器在cleanPaste的时候允许保留部分标签样式

### ISSUE THREAD

**Issue by iwege** [mycolorway/simditor#432]
希望能有一个简单的配置项允许保留指定的标签，默认是所有都清除。

有一些格式，比如`<sub>`,`<sup>`可能还是需要的。

**Comment by feng99** [comment]
你的cleanPaste设置为true后,生效?
可以贴下您的代码吗?^_^
我的不生效.
效果应该为:复制进去后,格式立刻消失.

**Comment by iwege** [comment]
我这边更改为true就是生效的。
