### ISSUE TITLE
如何判断编辑器内所有图片 是否已经上传完成?

### ISSUE THREAD

**Issue by hyyyp** [mycolorway/simditor#442]
当用户采用 上传图片时 , 上传需要一定时间,  编辑器采用了即时显示的方式很人性化,但用户却以为已经上传完毕  直接提交了表单.  
我就是想在提交表单的时候   判断编辑器内的所有图片是否已经都上传完成, 从而反馈一个alert

**Comment by RuochenLyu** [comment]
这不属于编辑器的功能，应该在上传组件里来实现，比如给上传过成功的图片加个遮罩。
