### ISSUE TITLE
如何获取当前光标位置和设置光标?

### ISSUE THREAD

**Issue by AlanYiNew** [mycolorway/simditor#443]
现在在做一个在线代码即时高亮的部分，每打一个字，hightlightjs渲染完代码，光标都会移位。有没有能设定光标位置的方法

**Comment by RuochenLyu** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Selection

Simditor 封装了一些 selection 的方法，[参见这里](https://github.com/mycolorway/simditor/blob/master/src/selection.coffee)
