### ISSUE TITLE
插入图片过大会撑开编辑器

### ISSUE THREAD

**Issue by qq245655664** [mycolorway/simditor#444]
而且把图片删除掉上下滚动页面有时编辑器也会撑大

**Comment by iamroma** [comment]
可以设置图片的 max-width 属性值为100%，使之自适应。 @qq245655664

**Comment by shitou0512** [comment]
@iamroma 能不能详细点，在哪里设置

**Comment by ydq** [comment]
@iamroma 实际上 我看了，simditor设置了img的 width和height属性，如果设置max-width的话，图片会变形。

**Comment by shitou0512** [comment]
怎么设置的  我是小白 能不能把你的那段带我给我看看，谢谢.

2016-06-20 

shitou 



发件人：ydq <notifications@github.com>
发送时间：2016-06-20 12:26
主题：Re: [mycolorway/simditor] 插入图片过大会撑开编辑器 (#444)
收件人："mycolorway/simditor"<simditor@noreply.github.com>
抄送："shitou0512"<shitou@16fan.com>,"Comment"<comment@noreply.github.com>

@iamroma 实际上 我看了，simditor设置了img的 width和height属性，如果设置max-width的话，图片会变形。

**Comment by iamroma** [comment]
@shitou0512 @ydq 你好。

@ydq 
单纯设置max-width的话，的确会使图片变形。解决办法可以再加个css属性控制高度自适应。这样的效果就会使img等比例缩放。具体我是这样设置的：

```
<style>
   img{ max-width:100%;height:auto;vertical-align: middle;}
</style>
```

@shitou0512 
在当前页面上加入这个css就可以。

**Comment by zhyuzhqq** [comment]
试试这样修改 

$img.attr({
                        src: src,
                        width: width,
                        height: height,
                        'data-image-size': width + ',' + height
                    }).removeClass('loading');


                    //以下为新增-----调整img尺寸适配editor
                    var parentjo = $img.parent();
                    console.log('editorjo width', parentjo.width());
                    if (img.width > parentjo.width()) {
                        $img.attr({
                            width: '100%',
                            height: 'auto'
                        });
                    };
                    //以上为新增-----调整img尺寸适配editor

**Comment by MertensMing** [comment]
设置 max-height 和 max-width 
```css
img {
    max-height: 100px;
    max-width: 100px;
}
```

**Comment by jdkcn** [comment]
@iamroma 的方法可以，不过最好不要设置所有的img。可以只限定到编辑器里面。

``` css
.simditor-body img {
	max-width: 98%;
	height: auto;
}
```

**Comment by Creabine** [comment]
@iamroma 多谢，本来准备在源码里判断尺寸修改，折腾了半天，还是你这个方法好
