### ISSUE TITLE
生成的toolbar中的部分图表垂直方向不居中，导致图标无法对齐

### ISSUE THREAD

**Issue by Creabine** [mycolorway/simditor#451]
在官网下载的demo也是如此，所有的toolbar图标都是顶在最顶而不是居中的。

**Comment by Creabine** [comment]
后来发现问题了，simditor.css文件中的.simditor .simditor-toolbar > ul > li > .toolbar-item span.fa {
  display: inline;
  line-height: normal;
}覆盖了.simditor .simditor-toolbar > ul > li > .toolbar-item中的line-height: 40px;
这应该算是个bug？

**Comment by RuochenLyu** [comment]
`.fa` 这个 class 应该在很久前就废弃了，你检查下是否使用的是最新版本的 simditor 呢。

**Comment by Creabine** [comment]
http://www.jq22.com/jquery-info590
我是在这边下载的，直接下载之后的index.html里边也是没有对齐的。是因为这边没更新么0.0

**Comment by RuochenLyu** [comment]
https://github.com/mycolorway/simditor/releases/tag/v2.3.6

**Comment by Creabine** [comment]
好的，非常感谢~很好用的插件=w=，继续加油呐
