### ISSUE TITLE
粘贴图片自动上传后，不替换URL

### ISSUE THREAD

**Issue by okwindows** [mycolorway/simditor#453]
通过浏览器复制图片后，粘贴后上传成功，但未替换URL。

**Comment by RuochenLyu** [comment]
[搜索](https://github.com/mycolorway/simditor/issues?utf8=%E2%9C%93&q=is%3Aissue%20%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87)

![image](https://cloud.githubusercontent.com/assets/1207465/16411573/4ab3fef6-3d5a-11e6-8b19-78ecfe783bc6.png)
