### ISSUE TITLE
为什么css中只有.woff的字体，没有.eot  .ttf这些？

### ISSUE THREAD

**Issue by BardMa** [mycolorway/simditor#455]
IE下字体丢失了

**Comment by ydq** [comment]
官方明确说明Supported Browsers: IE10+、Chrome、Firefox、Safari.
IE9以上就支持woff了，http://caniuse.com/#search=woff

**Comment by RuochenLyu** [comment]
[fort-d7611efe.zip](https://github.com/mycolorway/simditor/files/336627/fort-d7611efe.zip)

**Comment by BardMa** [comment]
非常感谢🙏
