### ISSUE TITLE
求最新版，有上传文件功能的新版。。。

### ISSUE THREAD

**Issue by zhyuzhqq** [mycolorway/simditor#457]
Simditor v2.3.6
http://simditor.tower.im/
2015-12-21
这个好像没有上传附件的功能啊
类似tower的这个按钮怎么打开
![image](https://cloud.githubusercontent.com/assets/20237926/16679819/2653d6e2-451d-11e6-8cd0-a1ca99f91ab7.png)

**Comment by angelaliang1988** [comment]
如何上传文件呢？求回复

**Comment by gengdaoping** [comment]
我也是在纠结上传功能

**Comment by huoduan** [comment]
感觉这编辑器功能太少了，靠我们自己扩展太费劲了
