### ISSUE TITLE
自定义工具条项目时工具条图标可能向上偏移

### ISSUE THREAD

**Issue by Creabine** [mycolorway/simditor#472]
使用最新版simditor，自定义工具条如：toolbar:['bold','italic','underline','ol','color'],

默认情况下图标会向上偏移。

测试发现，工具条中部分图标高度不足，所以自定义工具条时仅有高度不足的图标时，就会向上偏移。

**Comment by xiatianlong** [comment]
我使用的2.3.6版本，同样有此问题。
解决办法：
            注释掉simditor.css第284行的height属性
