### ISSUE TITLE
本地上传图片按钮响应很慢

### ISSUE THREAD

**Issue by Creabine** [mycolorway/simditor#473]
点击上传图片后，经过很久的延迟才会弹出文件选择框，长达3-5秒

**Comment by Clyde-Huang** [comment]
先去掉  input控件的 accept: 'image/*' 属性，或改为限制具体的图片格式,如: 'image/jpg'

**Comment by Creabine** [comment]
确实解决了，非常感谢

**Comment by ochukai** [comment]
这么简单 版本更新的时候能不能带上  这样没法用啊  特别是  我使用npm 安装 开发的其他小伙伴每次build就没了
