### ISSUE TITLE
标题和列表功能同时使用有冲突

### ISSUE THREAD

**Issue by endlllll** [mycolorway/simditor#474]
![image](https://cloud.githubusercontent.com/assets/3176953/17917808/495c47f6-69f2-11e6-98c7-2b827b98bd74.png)

![image](https://cloud.githubusercontent.com/assets/3176953/17917866/9ef9f49c-69f2-11e6-89ca-4ec344920b20.png)

**Comment by endlesslove1222** [comment]
![image](https://cloud.githubusercontent.com/assets/3176953/17917860/95ab526e-69f2-11e6-8ade-efe451d0cd99.png)
