### ISSUE TITLE
本地上传图片url一直都是dataurl，如何修改为链接形式的url？

### ISSUE THREAD

**Issue by cleanyoona** [mycolorway/simditor#477]
如题，我file_path已经返回了所需的url，但仍然显示data url的形式。

**Comment by ydq** [comment]
上传成功，且按如下json格式返回才会自动替换dataurl为上传后的url
```json
{
    "success":true,
    "file_path":"成功上传后的URL路径",
    "msg":"成功上传的消息，可忽略"
}
```

**Comment by cleanyoona** [comment]
result = Object {msg: "success", file_path: "http://localhost:8080/web…/showImage.do?imgAddress=1472519662063.jpeg", success: true}
我在upload.js里的success方法里面打了断点，这个是我的返回值，感觉没问题啊，求大神指点迷津。。。

**Comment by cleanyoona** [comment]
是不是loadImage方法里面的img.onload这个闭包缓存了src啊？貌似loadImage能进来两次但是img.onload只执行一次，里面的src是data url...

**Comment by cleanyoona** [comment]
没问题了，是我url截断符的问题。。。

**Comment by Jyhwenchai** [comment]
```
uploadsuccess: (data) => {
},
```
在这个回调里你拿到的就是下面这种格式的json吗，而下面这种json是有服务器返回的
```
{
    "success":true,
    "file_path":"成功上传后的URL路径",
    "msg":"成功上传的消息，可忽略"
}
```
