### ISSUE TITLE
上传图片按钮点击后反应非常慢

### ISSUE THREAD

**Issue by loktarjugg** [mycolorway/simditor#478]
我的环境是在vagrant下的，测试时打开上传图片非常慢，大概需要8秒－10秒左右。
根据 #473 手动更改了simditor.js后正常，但是这样明显不合理。。
下个版本能否把图片格式也作为参数 或者说有什么好的办法解决这个问题吗？

**Comment by imbyron** [comment]
同问。

**Comment by okwindows** [comment]
同问
