### ISSUE TITLE
本地上传图片响应时间很长

### ISSUE THREAD

**Issue by xxpeter** [mycolorway/simditor#486]
本地上传图片的input的标签属性accept="image/*"造成响应时间很长，不知道是否支持可配上传图片类型

**Comment by nodeman777** [comment]
这个应该是chrome的bug，你可以把image的类型列出写，就可以了

**Comment by xxpeter** [comment]
这样要改源代码，打包的时候每次都得改。。。

**Comment by nodeman777** [comment]
自己发个npm咯

**Comment by xxpeter** [comment]
好主意。。
