### ISSUE TITLE
html表格支持

### ISSUE THREAD

**Issue by nonStopWind** [mycolorway/simditor#531]
您好，麻烦问下，现在不能自动支持把表格语法转化为表格对吧？如果改成Markdown表格语法可以支持么？

下面这段html的表格，通过setvalue传递到编辑器，表格没有显示。

`<table border = 1px cellspacing = 0 width = 744><tr><th>车型</th><th>指导价（万元）</th><th>裸车价（万元）</th><th>优惠幅度（万元）</th></tr><tr><td>2018款  3.0 V6 SC 盛世版</td><td>125.8</td><td>125.8</td><td>0.0</td></tr><tr><td>2018款 3.0 V6 SC Vogue 传世版</td><td>139.8</td><td>139.27</td><td>0.53</td></tr><tr><td>2018款 3.0 V6 SC AB 尊崇创世加长版</td><td>197.8</td><td>195.77</td><td>2.03</td></tr><tr><td>2018款 5.0 V8 SC AB 尊崇创世加长版</td><td>264.8</td><td>264.77</td><td>0.03</td></tr><tr><td>2017款 5.0 V8 SC 巅峰创世加长版</td><td>332.8</td><td>332.77</td><td>0.03</td></tr></table>`

**Comment by biallo** [comment]
可以的，我用你提供的这段表格代码做了测试，没有出现问题。

**Comment by nonStopWind** [comment]
十分感谢biallo回复！想再麻烦问下是用了decorate来实现么？还是我没有定义必要的配置？

我是直接先如下初始化编辑器：
<script>
 var editor = new Simditor({
  textarea: $('#editor')

  //optional options
});
  </script>

然后处理ajex返回的包含html的Json，表格没有渲染出来。
<script>

  $("#generate").click(function(){
  
      editor.setValue('正在生成......')
      var seriesName = $('#series1NameId').val();
      var cityName = $('#cityId').val();
      
      console.log(seriesName);
      console.log(cityName);
 
      $.ajax({
        url: '/audition/ajax/priceOff1Article',
        data: {
          'seriesName': seriesName,
          'cityName': cityName
      },
        type: 'get',
        dataType: 'json',
        success: function (data) {
          
           dataType: 'json';
          
            var contentTest='';
            console.log($.parseJSON(data)); 
            $.each($.parseJSON(data), function(i, item){
                
               contentTest+=''+item+'\n'
               
               });
               //$('#articlePreview').html(contentTest);
               //$('#img_id').attr("src","http://car2.autoimg.cn/cardfs/product/g2/M07/25/61/u_autohomecar__wKgHaVo9LAuAC5WiAAMJgmS-KW8180.jpg");
               editor.setValue(contentTest);
               
              
              }    
      });
      
  });
  </script>


前端截图如下，表格没有显示出来：

![](https://ws3.sinaimg.cn/large/006tKfTcly1ftjpfo8nenj31kw0r1ai5.jpg)

十分感谢！

**Comment by biallo** [comment]
你好，从截图上来看的话，是因为你没有启用表格。

```
var editor = new Simditor({
  textarea: $('#editor'),
  toolbar: ['table'] // 只启用 table
});
```

更多的信息请查看 http://simditor.tower.im//docs/doc-config.html
